project:
  type: book
  output-dir: docs

book:
  title: "Dimensionality Reduction"
  author: "Olga Dethlefsen"
  # date: "8/31/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - ICA.qmd
    - SOM.qmd
    - tSNE-UMAP.qmd
    - diffusionMaps.qmd
    
bibliography: references.bib

format:
  html:
    theme: spacebar
    code-fold: true
    mermaid:
      theme: forest

    
    


