<!DOCTYPE html>
<html lang="en"><head>
<script src="session-lm-presentation_files/libs/clipboard/clipboard.min.js"></script>
<script src="session-lm-presentation_files/libs/quarto-html/tabby.min.js"></script>
<script src="session-lm-presentation_files/libs/quarto-html/popper.min.js"></script>
<script src="session-lm-presentation_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="session-lm-presentation_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="session-lm-presentation_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="session-lm-presentation_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.6.42">

  <title>Introduction to linear models</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="session-lm-presentation_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="session-lm-presentation_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="session-lm-presentation_files/libs/revealjs/dist/theme/quarto-9956cc7a85d8e51445fc2ea9fa92a92d.css">
  <link href="session-lm-presentation_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="session-lm-presentation_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="session-lm-presentation_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="session-lm-presentation_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="session-lm-presentation_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="session-lm-presentation_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Introduction to linear models</h1>

<div class="quarto-title-authors">
</div>

</section>
<section id="we-will-learn" class="slide level2">
<h2>We will learn</h2>
<ul>
<li>what are linear models</li>
<li>how to estimate model parameters</li>
<li>hypothesis testing on linear regression</li>
<li>evaluating how well model fits the data</li>
<li>model assumptions</li>
<li>linear model selection and regularization</li>
<li>GLM with logistic regression</li>
</ul>
</section>
<section id="what-does-a-linear-regression-give-us" class="slide level2">
<h2>What Does A Linear Regression Give us</h2>
<style>
    .arrow {
        width: 50px; 
        height: 10px;
    }
</style>

<div style="display: flex; align-items: center; justify-content: center; gap: 30px;">

    <!-- Left Side: Inputs -->
    <div style="display: flex; flex-direction: column; gap: 30px;">
        <div style="border: 2px solid black; background-color: lightgray; padding: 15px; border-radius: 10px; width: 250px; text-align: center;">
            <strong>Single numerical outcome:</strong><br>
            Weight, Gene Expression, Methylation Beta Values, …
        </div>

        <div style="border: 2px solid black; background-color: lightgray; padding: 15px; border-radius: 10px; width: 250px; text-align: center;">
            <strong>Numerical or categorical predictors:</strong><br>
            Height, Disease status, BMI, Glucose levels …
        </div>
    </div>

    <!-- Arrows pointing to Model -->
    <div style="display: flex; flex-direction: column; align-items: center; gap: 40px;">
        <svg class="arrow">
            <line x1="0" y1="5" x2="50" y2="5" stroke="black" stroke-width="2"></line>
            <polygon points="50,5 40,0 40,10" fill="black"></polygon>
        </svg>
        
        <svg class="arrow">
            <line x1="0" y1="5" x2="50" y2="5" stroke="black" stroke-width="2"></line>
            <polygon points="50,5 40,0 40,10" fill="black"></polygon>
        </svg>
    </div>

    <!-- Model Box (Center) -->
    <div style="background-color: black; color: white; padding: 20px; font-weight: bold; border-radius: 10px; width: 120px; text-align: center;">
        Model
    </div>

    <!-- Arrows pointing to Outputs -->
    <div style="display: flex; flex-direction: column; align-items: center; gap: 25px;">
        <svg class="arrow">
            <line x1="0" y1="5" x2="50" y2="5" stroke="black" stroke-width="2"></line>
            <polygon points="50,5 40,0 40,10" fill="black"></polygon>
        </svg>
        
        <svg class="arrow">
            <line x1="0" y1="5" x2="50" y2="5" stroke="black" stroke-width="2"></line>
            <polygon points="50,5 40,0 40,10" fill="black"></polygon>
        </svg>
        
        <svg class="arrow">
            <line x1="0" y1="5" x2="50" y2="5" stroke="black" stroke-width="2"></line>
            <polygon points="50,5 40,0 40,10" fill="black"></polygon>
        </svg>
    </div>

    <!-- Right Side: Outputs -->
    <div style="display: flex; flex-direction: column; gap: 30px;">
        <div style="border: 2px solid black; background-color: lightgray; padding: 15px; border-radius: 10px; width: 300px; text-align: center;">
            Is there any statistically meaningful relationship <br> between the outcome and any variables?
        </div>

        <div style="border: 2px solid black; background-color: lightgray; padding: 15px; border-radius: 10px; width: 300px; text-align: center;">
            How strong is the relationship?
        </div>

        <div style="border: 2px solid black; background-color: lightgray; padding: 15px; border-radius: 10px; width: 300px; text-align: center;">
            Come up with likely outcome based on new variables (prediction).
        </div>
    </div>

</div>
</section>
<section id="what-does-a-linear-regression-give-us-1" class="slide level2">
<h2>What Does A Linear Regression Give us</h2>
<style>
    .arrow {
        width: 50px; 
        height: 10px;
    }
</style>

<div style="display: flex; align-items: center; justify-content: center; gap: 30px;">

    <!-- Left Side: Inputs -->
    <div style="display: flex; flex-direction: column; gap: 30px;">
        <div style="border: 2px solid black; background-color: lightgray; padding: 15px; border-radius: 10px; width: 250px; text-align: center;">
            <strong>Single numerical outcome:</strong><br>
            <strong>Weight</strong>
        </div>

        <div style="border: 2px solid black; background-color: lightgray; padding: 15px; border-radius: 10px; width: 250px; text-align: center;">
            <strong>Numerical or categorical predictors:</strong><br>
            <strong>Height</strong>, <strong>Gender</strong>
        </div>
    </div>

    <!-- Arrows pointing to Model -->
    <div style="display: flex; flex-direction: column; align-items: center; gap: 40px;">
        <svg class="arrow">
            <line x1="0" y1="5" x2="50" y2="5" stroke="black" stroke-width="2"></line>
            <polygon points="50,5 40,0 40,10" fill="black"></polygon>
        </svg>
        
        <svg class="arrow">
            <line x1="0" y1="5" x2="50" y2="5" stroke="black" stroke-width="2"></line>
            <polygon points="50,5 40,0 40,10" fill="black"></polygon>
        </svg>
    </div>

    <!-- Model Box (Center) -->
    <div style="background-color: black; color: white; padding: 20px; font-weight: bold; border-radius: 10px; width: 120px; text-align: center;">
        Model
    </div>

    <!-- Arrows pointing to Outputs -->
    <div style="display: flex; flex-direction: column; align-items: center; gap: 25px;">
        <svg class="arrow">
            <line x1="0" y1="5" x2="50" y2="5" stroke="black" stroke-width="2"></line>
            <polygon points="50,5 40,0 40,10" fill="black"></polygon>
        </svg>
        
        <svg class="arrow">
            <line x1="0" y1="5" x2="50" y2="5" stroke="black" stroke-width="2"></line>
            <polygon points="50,5 40,0 40,10" fill="black"></polygon>
        </svg>
        
        <svg class="arrow">
            <line x1="0" y1="5" x2="50" y2="5" stroke="black" stroke-width="2"></line>
            <polygon points="50,5 40,0 40,10" fill="black"></polygon>
        </svg>
    </div>

    <!-- Right Side: Outputs -->
    <div style="display: flex; flex-direction: column; gap: 30px;">
        <div style="border: 2px solid black; background-color: lightgray; padding: 15px; border-radius: 10px; width: 350px; text-align: center;">
            <strong>Relationship:</strong><br>
            Does <strong>Height</strong> affect <strong>Weight</strong>?<br>
            Do different genders influence weight?
        </div>

        <div style="border: 2px solid black; background-color: lightgray; padding: 15px; border-radius: 10px; width: 350px; text-align: center;">
            <strong>Relative magnitude:</strong><br>
            How much does weight increase if a female grows taller by 2cm?
        </div>

        <div style="border: 2px solid black; background-color: lightgray; padding: 15px; border-radius: 10px; width: 350px; text-align: center;">
            <strong>Prediction:</strong><br>
            What's the weight of a male with a height of 3 meters?
        </div>
    </div>

</div>
</section>
<section id="simple-example" class="slide level2">
<h2>Simple example</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>We administered Drug X at increasing weight-based doses (mg/kg) to evaluate its effect on recovery time in a controlled experimental setting.</p>
<p><strong>Is there any relationship between dosage (mg) and recovery time (days)?</strong></p>
<div class="r-stack">
<div class="fragment fade-in-then-out" data-fragment-index="1">
<p><span class="math inline">\(Recovery\ time = dosage\)</span></p>
</div>
<div class="fragment fade-in" data-fragment-index="2">
<p>If recovery time always increases at the same rate as dosage, we might guess:</p>
<p><span class="math inline">\(Recovery\ time = dosage \times \textbf{some effect}\)</span></p>
<p>For example:</p>
<p><span class="math inline">\(Recovery\ time = dosage \times \textbf{3}\)</span></p>
</div>
</div>
<div class="fragment fade-in" data-fragment-index="3">
<p><span class="math inline">\(Recovery\ time = \textbf{baseline} + dosage \times \textbf{3}\)</span></p>
</div>
</div><div class="column" style="width:5%;">

</div><div class="column" style="width:45%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="session-lm-presentation_files/figure-revealjs/unnamed-chunk-2-1.png" width="576"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="simple-example---prediction" class="slide level2">
<h2>Simple example - prediction</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>If we use this form now, will it predict recovery time exactly for every person?</p>
<p><span class="math inline">\(Recovery\ time = \textbf{baseline} + dosage \times \textbf{some effect}\)</span></p>
</div><div class="column" style="width:5%;">

</div><div class="column" style="width:45%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="session-lm-presentation_files/figure-revealjs/unnamed-chunk-3-1.png" width="576"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="simple-example---prediction-1" class="slide level2">
<h2>Simple example - prediction</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>If we use this form now, will it predict recovery time exactly for every person?</p>
<p><span class="math inline">\(Predicted Recovery\ time = \textbf{47.84} + dosage \times \textbf{2.88}\)</span></p>
</div><div class="column" style="width:5%;">

</div><div class="column" style="width:45%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="session-lm-presentation_files/figure-revealjs/unnamed-chunk-4-1.png" width="576"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="simple-example---prediction-2" class="slide level2">
<h2>Simple example - prediction</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>If we use this form now, will it predict recovery time exactly for every person?</p>
<p><span class="math display">\[
\begin{aligned}
    \text{Recovery Time} &amp;= \color{blue}{\mathbf{47.84} + \text{dosage}} \times \mathbf{2.88} \\
    &amp;+ \color{red}{\fbox{error}}
\end{aligned}
\]</span></p>
<p><span class="math display">\[\text{Recovery time}_i = \textbf{baseline} + dosage_i \times \\\textbf{effect} + \textbf{error}_i\]</span></p>
</div><div class="column" style="width:5%;">

</div><div class="column" style="width:45%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="session-lm-presentation_files/figure-revealjs/unnamed-chunk-5-1.png" width="576"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="simple-example---prediction-3" class="slide level2">
<h2>Simple example - prediction</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>If we use this form now, will it predict recovery time exactly for every person?</p>
<p><span class="math display">\[
\begin{aligned}
    \text{Recovery Time} &amp;= \color{blue}{\mathbf{47.84} + \text{dosage}} \times \mathbf{2.88} \\
    &amp;+ \color{red}{\fbox{error}}
\end{aligned}
\]</span></p>
<div class="bottom-table" style="position: absolute; bottom: 0">
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;">dosage</th>
<th style="text-align: right;">recovery</th>
<th style="text-align: right;">predicted</th>
<th style="text-align: right;">error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1.322746</td>
<td style="text-align: right;">54.88094</td>
<td style="text-align: right;">51.64948</td>
<td style="text-align: right;">3.231466</td>
</tr>
<tr class="even">
<td style="text-align: right;">5.195825</td>
<td style="text-align: right;">64.00759</td>
<td style="text-align: right;">62.80361</td>
<td style="text-align: right;">1.203978</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div><div class="column" style="width:5%;">

</div><div class="column" style="width:45%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="session-lm-presentation_files/figure-revealjs/unnamed-chunk-7-1.png" width="576"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="simple-example---deciding-the-baseline-and-effect-size" class="slide level2">
<h2>Simple example - deciding the baseline and effect size</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>How do we decide on the baseline and the effect</p>
<div class="fragment fade-in" data-fragment-index="2">
<p><span class="math display">\[\text{Recovery time}_i = \textbf{baseline} + dosage_i \times \\\textbf{effect} + \color{red}{\textbf{error}_i}\]</span> <strong>We want to have lowest error for each individual!</strong></p>
</div>
<div class="bottom-table" style="position: absolute; bottom: 0">
<div class="cell" data-layout-valign="bottom">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;">dosage</th>
<th style="text-align: right;">recovery</th>
<th style="text-align: right;">predicted</th>
<th style="text-align: right;">error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1.322746</td>
<td style="text-align: right;">54.88094</td>
<td style="text-align: right;">51.64948</td>
<td style="text-align: right;">3.231466</td>
</tr>
<tr class="even">
<td style="text-align: right;">5.195825</td>
<td style="text-align: right;">64.00759</td>
<td style="text-align: right;">62.80361</td>
<td style="text-align: right;">1.203978</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div><div class="column" style="width:5%;">

</div><div class="column" style="width:45%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="session-lm-presentation_files/figure-revealjs/unnamed-chunk-9-1.png" width="576"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="simple-example---deciding-the-baseline-and-effect-size-1" class="slide level2">
<h2>Simple example - deciding the baseline and effect size</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>How do we decide on the baseline and the effect</p>
<p><span class="math display">\[\text{Recovery time}_i = \textbf{47.84} + dosage_i \times \\\textbf{1.5} + {\textbf{error}_i}\]</span></p>
</div><div class="column" style="width:5%;">

</div><div class="column" style="width:45%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="session-lm-presentation_files/figure-revealjs/unnamed-chunk-10-1.png" width="576"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="simple-example---deciding-the-baseline-and-effect-size-2" class="slide level2">
<h2>Simple example - deciding the baseline and effect size</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>How do we decide on the baseline and the effect</p>
<p><span class="math display">\[\text{Recovery time}_i = \textbf{47.84} + dosage_i \times \\\textbf{4.5} + {\textbf{error}_i}\]</span></p>
</div><div class="column" style="width:5%;">

</div><div class="column" style="width:45%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="session-lm-presentation_files/figure-revealjs/unnamed-chunk-11-1.png" width="576"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="simple-example---deciding-the-baseline-and-effect-size-3" class="slide level2">
<h2>Simple example - deciding the baseline and effect size</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>How do we decide on the baseline and the effect <span class="math display">\[\text{Recovery time}_i = \textbf{47.84} + dosage_i \times \\\textbf{2.8} + {\textbf{error}_i}\]</span></p>
<div>
<ul>
<li class="fragment"><span class="math inline">\({\textbf{error}^2_1}+{\textbf{error}^2_2}+{\textbf{error}^2_3}+...+{\textbf{error}^2_n}\)</span></li>
<li class="fragment"><span class="math inline">\(\text{error}_i = \text{Recovery time}_i - baseline + dosage_i \times \\ \text{effect}\)</span></li>
</ul>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="session-lm-presentation_files/figure-revealjs/unnamed-chunk-12-1.png" width="576"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:5%;">

</div><div class="column" style="width:45%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="session-lm-presentation_files/figure-revealjs/unnamed-chunk-13-1.png" width="576"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="what-if-we-have-more-than-one-predictor" class="slide level2">
<h2>What if we have more than one predictor</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>We believe that the effects are added together</p>
<p><span class="math display">\[
\text{Recovery time}_i = \textbf{baseline} + dosage_i \times \\\textbf{effect}_1 + dosage2 \times \textbf{effect}_2+{\textbf{error}_i}
\]</span></p>
</div><div class="column" style="width:5%;">

</div><div class="column" style="width:45%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="session-lm-presentation_files/figure-revealjs/unnamed-chunk-14-1.png" width="576"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="more-formal-definitation" class="slide level2">
<h2>More formal definitation</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>If we want to have a little bit more formal definition:</p>
<ul>
<li>baseline is called <em>intercept</em> and is shown by <span class="math inline">\(\alpha\)</span></li>
<li>effects are called <em>coefficients</em> and are shown by <span class="math inline">\(\beta\)</span></li>
<li>the errors are called residuals and are shown by <span class="math inline">\(\epsilon\)</span></li>
</ul>
<p>So our model becomes:</p>
<ul>
<li><span id="eq-lm"><span class="math display">\[Y_i = \alpha + \beta \cdot x_i + \epsilon_i \qquad(1)\]</span></span> where:</li>
<li><span class="math inline">\(x\)</span>: is called: exposure variable, explanatory variable, independent variable, predictor, covariate</li>
<li><span class="math inline">\(y\)</span>: is called: response, outcome, dependent variable</li>
</ul>
</div><div class="column" style="width:5%;">

</div><div class="column" style="width:45%;">

</div></div>
</section>
<section id="the-line-slope-and-intercept" class="slide level2">
<h2>The Line: Slope and Intercept</h2>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li>The regression model defines a <strong>line</strong>.</li>
<li>This line has two important parts:
<ul>
<li><strong>Intercept</strong> (<span class="math inline">\(\alpha\)</span>): Where the line crosses the y-axis (baseline when <span class="math inline">\(x=0\)</span>)</li>
<li><strong>Slope</strong> (<span class="math inline">\(\beta\)</span>): How much <span class="math inline">\(y\)</span> changes for a one-unit increase in <span class="math inline">\(x\)</span></li>
</ul></li>
<li>The formal model is: <span class="math display">\[Y_i = \alpha + \beta \cdot x_i + \epsilon_i\]</span></li>
</ul>
</div><div class="column" style="width:5%;">

</div><div class="column" style="width:45%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="session-lm-presentation_files/figure-revealjs/unnamed-chunk-15-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="least-squares" class="slide level2">
<h2>Least squares</h2>
<ul>
<li>in the above example, the values of <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta\)</span> have just appeared</li>
<li>in practice, <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta\)</span> values are <strong>unknown</strong> and we use data to <strong>estimate these coefficients</strong>, noting the estimates with a <strong>hat</strong>, <span class="math inline">\(\hat{\alpha}\)</span> and <span class="math inline">\(\hat{\beta}\)</span></li>
<li><strong>least squares</strong> is one of the methods of parameters estimation, i.e.&nbsp;finding <span class="math inline">\(\hat{\alpha}\)</span> and <span class="math inline">\(\hat{\beta}\)</span></li>
</ul>
</section>
<section id="least-squares-1" class="slide level2 smaller">
<h2>Least squares</h2>
<p><em>minimizing RSS (fitting the model)</em></p>
<div class="columns">
<div class="column" style="width:50%;">
<p>Let <span class="math inline">\(\hat{y_i}=\hat{\alpha} + \hat{\beta}x_i\)</span> be the prediction <span class="math inline">\(y_i\)</span> based on the <span class="math inline">\(i\)</span>-th value of <span class="math inline">\(x\)</span>:</p>
<ul>
<li>Then <span class="math inline">\(\epsilon_i = y_i - \hat{y_i}\)</span> represents the <span class="math inline">\(i\)</span>-th <strong>residual</strong>, i.e.&nbsp;the difference between the <span class="math inline">\(i\)</span>-th observed response value and the <span class="math inline">\(i\)</span>-th response value that is predicted by the linear model</li>
<li>RSS, the <strong>residual sum of squares</strong> is defined as: <span class="math display">\[RSS = \epsilon_1^2 + \epsilon_2^2 + \dots + \epsilon_n^2\]</span> or equivalently as: <span class="math display">\[RSS=(y_1-\hat{\alpha}-\hat{\beta}x_1)^2+(y_2-\hat{\alpha}-\hat{\beta}x_2)^2\\ +...+(y_n-\hat{\alpha}-\hat{\beta}x_n)^2\]</span></li>
<li>the least squares approach chooses <span class="math inline">\(\hat{\alpha}\)</span> and <span class="math inline">\(\hat{\beta}\)</span> <strong>to minimize the RSS</strong>.</li>
</ul>
</div><div class="column" style="width:10%;">

</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="session-lm-presentation_files/figure-revealjs/unnamed-chunk-16-1.png" class="margin-caption" width="768"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="common-cases" class="slide level2 smaller">
<h2>Common cases</h2>
<p><em>Understand common models</em></p>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li>There are a large number of simple and complex models that can be fitted using linear models</li>
<li>We will have a look at a few examples:
<ul>
<li>Simple regression using a single continuous predictor</li>
<li>Simple regression using a single categorical predictor</li>
<li>Multiple regression using two continuous predictors</li>
<li>Multiple regression using one continuous predictor and one categorical predictor</li>
<li>Multiple regression using two categorical predictors</li>
<li>Multiple regression interaction of various predictors</li>
</ul></li>
</ul>
</div><div class="column" style="width:10%;">

</div><div class="column" style="width:40%;">

</div></div>
</section>
<section id="simple-regression-using-a-single-continuous-predictor" class="slide level2">
<h2>Simple regression using a single continuous predictor</h2>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li>We have only a single continuous predictor</li>
<li>The model we fit is: <span class="math display">\[Y_i = \alpha + \beta \cdot x_i + \epsilon_i\]</span></li>
</ul>
<div>
<ul>
<li class="fragment">Intercept (<span class="math inline">\(\alpha\)</span>): When dosage is 0 mg, the predicted recovery time is 47.84 days.</li>
<li class="fragment">Slope (<span class="math inline">\(\beta\)</span>): For each additional mg of dosage, the recovery time increases by 2.88 days on average.</li>
</ul>
</div>
<div class="bottom-table" style="position: absolute; bottom: 0">
<div class="sourceCode" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href=""></a>model<span class="ot">&lt;-</span><span class="fu">lm</span>(recoveryTime<span class="sc">~</span>dosage,<span class="at">data=</span>data)</span>
<span id="cb1-2"><a href=""></a><span class="fu">print</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = recoveryTime ~ dosage, data = data)

Coefficients:
(Intercept)       dosage  
      47.84         2.88  </code></pre>
</div>
</div>
</div>
</div><div class="column" style="width:10%;">

</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="session-lm-presentation_files/figure-revealjs/unnamed-chunk-19-1.png" class="margin-caption" width="768"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="simple-regression-using-a-single-categorical-predictor" class="slide level2">
<h2>Simple regression using a single categorical predictor</h2>
<div class="columns">
<div class="column" style="white-space: normal; word-wrap: break-word; font-size: 80%;">
<div class="smaller">
<ul>
<li>We have only a single <strong>categorical</strong> predictor.</li>
<li>Depending on how many <em>levels</em> the predictor has, R will create dummy variables.</li>
<li>In this example, the categorical variable <em>treatment</em> has <strong>two levels</strong>: A and B.</li>
<li>R automatically uses the <strong>first level alphabetically</strong> (here: A) as the <strong>reference level</strong>.</li>
<li>The model we fit is:<br>
<span class="math display">\[Y_i = \alpha + \beta_1 \cdot \text{B}_i + \epsilon_i\]</span><br>
where:
<ul>
<li><span class="math inline">\(\text{B}_i = 1\)</span> if treatment is B, 0 otherwise</li>
</ul></li>
</ul>
<div>
<p><strong>Interpretation of coefficients:</strong></p>
<ul>
<li class="fragment"><strong>Intercept (66.75):</strong> The predicted recovery time for treatment <strong>A</strong> (reference group) is 66.75 days.</li>
<li class="fragment"><strong>treatment B (-78.27):</strong> Treatment <strong>B</strong> is associated with <strong>-78.27 days shorter</strong> recovery time compared to A.</li>
</ul>
</div>
</div>
</div><div class="column" style="width:10%;">

</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="session-lm-presentation_files/figure-revealjs/unnamed-chunk-21-1.png" class="margin-caption" width="768"></p>
</figure>
</div>
</div>
</div>
<div class="bottom-table" style="position: absolute; bottom: 0">
<div class="sourceCode" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href=""></a>model<span class="ot">&lt;-</span><span class="fu">lm</span>(recoveryTime<span class="sc">~</span>treatment,<span class="at">data=</span>data)</span>
<span id="cb3-2"><a href=""></a><span class="fu">print</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = recoveryTime ~ treatment, data = data)

Coefficients:
(Intercept)   treatmentB  
      66.75       -78.27  </code></pre>
</div>
</div>
</div>
</div></div>
</section>
<section id="multiple-regression-using-two-continuous-predictors" class="slide level2">
<h2>Multiple regression using two continuous predictors</h2>
<div class="columns">
<div class="column" style="white-space: normal; word-wrap: break-word; font-size: 80%;">
<div class="smaller">
<ul>
<li>In this example, we model recovery time using two continuous predictors: <em>dosage</em> and <em>dosage2</em>.</li>
<li>The model we fit is:<br>
<span class="math display">\[Y_i = \alpha + \beta_1 \cdot \text{dosage}_i + \beta_2 \cdot \text{dosage2}_i + \epsilon_i\]</span></li>
<li>This model fits a <strong>regression plane</strong> in 3D space.</li>
</ul>
<hr>
<div>
<p><strong>Interpretation of coefficients:</strong></p>
<ul>
<li class="fragment"><strong>Intercept (49.85)</strong>: Predicted recovery time when both predictors are 0.</li>
<li class="fragment"><strong>dosage (3.08)</strong>: Effect of dosage, controlling for dosage2</li>
<li class="fragment"><strong>dosage2 (0.0041)</strong>: Effect of dosage2, controlling for dosage.</li>
</ul>
</div>
</div>
</div><div class="column" style="width:10%;">

</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="session-lm-presentation_files/figure-revealjs/unnamed-chunk-24-1.png" class="margin-caption" width="768"></p>
</figure>
</div>
</div>
</div>
<div class="bottom-table" style="position: absolute; bottom: 0">
<div class="sourceCode" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href=""></a>model<span class="ot">&lt;-</span><span class="fu">lm</span>(recoveryTime<span class="sc">~</span>dosage<span class="sc">+</span>dosage2,<span class="at">data=</span>data)</span>
<span id="cb5-2"><a href=""></a><span class="fu">print</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = recoveryTime ~ dosage + dosage2, data = data)

Coefficients:
(Intercept)       dosage      dosage2  
  49.849228     3.076454     0.004118  </code></pre>
</div>
</div>
</div>
</div></div>
</section>
<section id="multiple-regression-using-one-continuous-predictor-and-one-categorical-predictor" class="slide level2">
<h2>Multiple regression using one continuous predictor and one categorical predictor</h2>
<div class="columns">
<div class="column" style="white-space: normal; word-wrap: break-word; font-size: 60%;">
<ul>
<li>In this example, we model <strong>recovery time</strong> using:
<ul>
<li>One <strong>continuous</strong> predictor: <em>dosage</em></li>
<li>One <strong>categorical</strong> predictor: <em>treatment</em> (with levels A and B)</li>
</ul></li>
<li>R automatically creates <strong>dummy variables</strong> for <em>treatment</em>, using <strong>A</strong> as the reference group.</li>
<li>The model we fit is:<br>
<span class="math display">\[Y_i = \alpha + \beta_1 \cdot \text{dosage}_i + \beta_2 \cdot \text{B}_i + \epsilon_i\]</span><br>
where:
<ul>
<li><span class="math inline">\(\text{B}_i = 1\)</span> if treatment is B, 0 otherwise</li>
</ul></li>
</ul>
<hr>
<div>
<p><strong>Interpretation of coefficients:</strong></p>
<ul>
<li class="fragment"><strong>Intercept (63.28):</strong><br>
Predicted recovery time for a person in treatment group A with dosage = 0.</li>
<li class="fragment"><strong>dosage (0.63):</strong><br>
For each additional mg of dosage, recovery time increases by <strong>0.63 days</strong>, <strong>controlling for treatment group</strong>.</li>
<li class="fragment"><strong>treatmentB (-78.41):</strong><br>
Individuals in group B recover <strong>-78.41 days faster</strong> than those in group A (reference), at the same dosage.</li>
</ul>
</div>
</div><div class="column" style="width:10%;">

</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="session-lm-presentation_files/figure-revealjs/unnamed-chunk-27-1.png" class="margin-caption" width="768"></p>
</figure>
</div>
</div>
</div>
<div class="bottom-table" style="position: absolute; bottom: 0">
<div class="sourceCode" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href=""></a>data <span class="ot">&lt;-</span> data_int_interaction</span>
<span id="cb7-2"><a href=""></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(recoveryTime <span class="sc">~</span> dosage <span class="sc">+</span> treatment, <span class="at">data =</span> data)</span>
<span id="cb7-3"><a href=""></a><span class="fu">print</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = recoveryTime ~ dosage + treatment, data = data)

Coefficients:
(Intercept)       dosage   treatmentB  
    63.2791       0.6322     -78.4131  </code></pre>
</div>
</div>
</div>
</div></div>
</section>
<section id="multiple-regression-using-two-categorical-predictors" class="slide level2">
<h2>Multiple regression using two categorical predictors</h2>
<div class="columns">
<div class="column" style="white-space: normal; word-wrap: break-word; font-size: 60%;">
<ul>
<li>In this example, we model <strong>recovery time</strong> using:
<ul>
<li>Two <strong>categorical</strong> predictors: <em>treatment</em> (levels A and B) and <em>doctor</em> (levels 1 and 2)</li>
</ul></li>
<li>R automatically creates <strong>dummy variables</strong>, using the <strong>first level</strong> as the reference:
<ul>
<li>Reference levels: <strong>treatment A</strong> and <strong>doctor 1</strong></li>
</ul></li>
<li>The model we fit is:</li>
</ul>
<p><span class="math display">\[
  \text{recoveryTime}_i = \alpha + \beta_1 \cdot \text{treatmentB}_i  + \beta_2 \cdot \text{doctor2}_i + \epsilon_i
\]</span></p>
<hr>
<div>
<p><strong>Interpretation of coefficients:</strong></p>
<ul>
<li class="fragment"><strong>Intercept (64.02):</strong><br>
Mean recovery time for patients with <strong>treatment A</strong> and <strong>doctor 1</strong>.</li>
<li class="fragment"><strong>treatmentB (-77.67):</strong><br>
Patients with <strong>treatment B</strong> recover <strong>-77.67 days faster</strong> than those with treatment A (doctor held constant).</li>
<li class="fragment"><strong>doctor2 (4.79):</strong><br>
Patients treated by <strong>doctor 2</strong> take <strong>4.79 days longer</strong> to recover than those treated by doctor 1 (treatment held constant).</li>
</ul>
</div>
</div><div class="column" style="width:10%;">

</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="session-lm-presentation_files/figure-revealjs/unnamed-chunk-30-1.png" class="margin-caption" width="768"></p>
</figure>
</div>
</div>
</div>
<div class="bottom-table" style="position: absolute; bottom: 0">
<div class="sourceCode" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href=""></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(recoveryTime <span class="sc">~</span> treatment <span class="sc">+</span> doctor, <span class="at">data =</span> data)</span>
<span id="cb9-2"><a href=""></a><span class="fu">print</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = recoveryTime ~ treatment + doctor, data = data)

Coefficients:
(Intercept)   treatmentB      doctor2  
     64.018      -77.667        4.794  </code></pre>
</div>
</div>
</div>
</div></div>
</section>
<section id="multiple-regression-interaction-of-various-predictors" class="slide level2 smaller">
<h2>Multiple regression interaction of various predictors</h2>
<p><em>Two categorical predictors with interaction</em></p>
<div class="columns">
<div class="column" style="white-space: normal; word-wrap: break-word; font-size: 80%;">
<ul>
<li>In this example, we model <strong>recovery time</strong> using:
<ul>
<li>Two <strong>categorical</strong> predictors: <em>treatment</em> (levels A and B) and <em>doctor</em> (levels 1 and 2)</li>
</ul></li>
<li>R automatically creates <strong>dummy variables</strong>, using the <strong>first level</strong> as the reference:
<ul>
<li>Reference levels: <strong>treatment A</strong> and <strong>doctor 1</strong></li>
</ul></li>
<li>The model now includes an <strong>interaction</strong> between treatment and doctor:<br>
This allows the effect of treatment to vary across doctors, and vice versa.</li>
<li>The model we fit is:</li>
</ul>
<p><span class="math display">\[
\text{recoveryTime}_i = \alpha + \beta_1 \cdot \text{treatmentB}_i + \beta_2 \cdot \text{doctor2}_i + \beta_3 \cdot (\text{treatmentB}_i \times \text{doctor2}_i) + \epsilon_i
\]</span></p>
<hr>
<div>
<p><strong>Interpretation of coefficients:</strong></p>
<ul>
<li class="fragment"><p><strong>Intercept (63.07):</strong><br>
Mean recovery time for <strong>treatment A</strong> with <strong>doctor 1</strong>.</p></li>
<li class="fragment"><p><strong>treatmentB (-75.97):</strong><br>
Effect of <strong>treatment B</strong> compared to A when <strong>doctor = 1</strong>.</p></li>
<li class="fragment"><p><strong>doctor2 (6.45):</strong><br>
Effect of <strong>doctor 2</strong> compared to doctor 1 when <strong>treatment = A</strong>.</p></li>
<li class="fragment"><p><strong>treatmentB:doctor2 (-3.36):</strong><br>
Additional effect (interaction) when <strong>treatment B</strong> is combined with <strong>doctor 2</strong>.</p></li>
<li class="fragment"><p><strong>Interpretation of interaction:</strong><br>
<span class="math inline">\(\beta_3\)</span> represents the <strong>difference of differences</strong>:</p></li>
<li class="fragment"><p><span class="math inline">\(\beta_3 = (\text{B vs A for doctor 2}) - (\text{B vs A for doctor 1}) = (\mu_{B2} - \mu_{A2}) - (\mu_{B1} - \mu_{A1})\)</span></p></li>
</ul>
</div>
</div><div class="column" style="width:10%;">

</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="session-lm-presentation_files/figure-revealjs/unnamed-chunk-33-1.png" class="margin-caption" width="768"></p>
</figure>
</div>
</div>
</div>
<div class="bottom-table" style="position: absolute; bottom: 0">
<div class="sourceCode" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href=""></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(recoveryTime <span class="sc">~</span> treatment <span class="sc">*</span> doctor, <span class="at">data =</span> data)</span>
<span id="cb11-2"><a href=""></a><span class="fu">print</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = recoveryTime ~ treatment * doctor, data = data)

Coefficients:
       (Intercept)          treatmentB             doctor2  treatmentB:doctor2  
            63.073             -75.966               6.454              -3.362  </code></pre>
</div>
</div>
</div>
</div></div>
</section>
<section id="multiple-regression-interaction-of-various-predictors-1" class="slide level2 smaller">
<h2>Multiple regression interaction of various predictors</h2>
<p><em>One categorical and one continuous predictors with interaction</em></p>
<div class="columns">
<div class="column" style="white-space: normal; word-wrap: break-word; font-size: 80%;">
<ul>
<li><p>In this example, we model <strong>recovery time</strong> using:</p>
<ul>
<li>One <strong>categorical</strong> predictor: <em>treatment</em> (levels A and B)</li>
<li>One <strong>continuous</strong> predictor: <em>dosage</em></li>
</ul></li>
<li><p>R automatically creates <strong>dummy variables</strong> for <em>treatment</em>, using <strong>treatment A</strong> as the reference.</p></li>
<li><p>The model includes an <strong>interaction</strong> between <em>treatment</em> and <em>dosage</em>:<br>
This allows the effect (slope) of dosage to be <strong>different for each treatment group</strong>.</p></li>
<li><p>The model fitted is: <span class="math display">\[
\text{recoveryTime}_i = \alpha + \beta_1 \cdot \text{treatmentB}_i + \beta_3 \cdot \text{dosage}_i + \\
\beta_4 \cdot (\text{treatmentB}_i \times \text{dosage}_i) + \epsilon_i
\]</span></p></li>
</ul>
<hr>
<div>
<p><strong>Interpretation of coefficients:</strong></p>
<ul>
<li class="fragment"><p><strong>Intercept (49.85):</strong><br>
Expected recovery time for a person in <strong>treatment A</strong> with <strong>dosage = 0</strong>.</p></li>
<li class="fragment"><p><strong>treatmentB (-51.01):</strong><br>
When dosage = 0, patients in treatment B recover <strong>-51.01 days faster</strong> than those in treatment A.</p></li>
<li class="fragment"><p><strong>dosage (3.08):</strong><br>
For treatment A, every 1 unit increase in dosage increases recovery time by <strong>3.08 days</strong>.</p></li>
<li class="fragment"><p><strong>treatmentB:dosage (-4.89):</strong><br>
The <strong>slope of dosage</strong> for treatment B is <strong>5.04 units lower</strong> than for treatment A.</p></li>
</ul>
</div>
</div><div class="column" style="width:10%;">

</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="session-lm-presentation_files/figure-revealjs/unnamed-chunk-36-1.png" class="margin-caption" width="768"></p>
</figure>
</div>
</div>
</div>
<div class="bottom-table" style="position: absolute; bottom: 0">
<div class="sourceCode" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href=""></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(recoveryTime <span class="sc">~</span> treatment <span class="sc">*</span> dosage,</span>
<span id="cb13-2"><a href=""></a><span class="at">data =</span> data)</span>
<span id="cb13-3"><a href=""></a><span class="fu">print</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = recoveryTime ~ treatment * dosage, data = data)

Coefficients:
      (Intercept)         treatmentB             dosage  treatmentB:dosage  
           49.851            -51.009              3.080             -4.892  </code></pre>
</div>
</div>
</div>
</div></div>
</section>
<section id="multiple-regression-interaction-of-continuous-predictors" class="slide level2 smaller">
<h2>Multiple regression interaction of continuous predictors</h2>
<p><em>Interaction between two continuous predictors</em></p>
<div class="columns">
<div class="column" style="white-space: normal; word-wrap: break-word; font-size: 80%;">
<ul>
<li><p>In this example, we model <strong>recovery time</strong> using two <strong>continuous</strong> predictors:</p>
<ul>
<li><em>dosage</em></li>
<li><em>dosage2</em></li>
</ul></li>
<li><p>The model includes an <strong>interaction term</strong> to allow the effect of one variable to change depending on the level of the other.</p></li>
<li><p>The fitted model is: <span class="math display">\[
\text{recoveryTime}_i = \alpha + \beta_1 \cdot \text{dosage}_i + \beta_2 \cdot \text{dosage2}_i + \beta_3 \cdot (\text{dosage}_i \times \text{dosage2}_i) + \epsilon_i
\]</span></p></li>
</ul>
<hr>
<div>
<p><strong>Interpretation of coefficients:</strong></p>
<ul>
<li class="fragment"><p><strong>Intercept (51.6):</strong><br>
Predicted recovery time when both <em>dosage</em> and <em>dosage2</em> = 0.</p></li>
<li class="fragment"><p><strong>dosage (2.74):</strong><br>
When <em>dosage2 = 0</em>, increasing <em>dosage</em> by 1 unit increases recovery time by <strong>2.74 days</strong>.</p></li>
<li class="fragment"><p><strong>dosage2 (-0.42):</strong><br>
When <em>dosage = 0</em>, increasing <em>dosage2</em> by 1 unit decreases recovery time by <strong>-0.42 days</strong>.</p></li>
<li class="fragment"><p><strong>dosage:dosage2 (0.07):</strong><br>
This is the <strong>interaction term</strong>. It means:</p>
<blockquote>
<p>The effect of <em>dosage</em> <strong>increases by 0.07</strong> for each 1-unit increase in <em>dosage2</em>, and vice versa.</p>
</blockquote></li>
</ul>
<hr>
<p><strong>How to interpret the interaction:</strong></p>
<ul>
<li class="fragment">If <strong>interaction = 0</strong>, the relationship between <em>dosage</em> and <em>recoveryTime</em> would be <strong>the same regardless of <em>dosage2</em></strong>.</li>
<li class="fragment">Since the interaction is <strong>positive</strong>, increasing <em>dosage2</em> <strong>strengthen</strong> the positive effect of <em>dosage</em>.</li>
</ul>
</div>
</div><div class="column" style="width:10%;">

</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="session-lm-presentation_files/figure-revealjs/unnamed-chunk-39-1.png" class="margin-caption" width="768"></p>
</figure>
</div>
</div>
</div>
<div class="bottom-table" style="position: absolute; bottom: 0">
<div class="sourceCode" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href=""></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(recoveryTime <span class="sc">~</span> dosage<span class="sc">*</span>dosage2,</span>
<span id="cb15-2"><a href=""></a><span class="at">data =</span> data)</span>
<span id="cb15-3"><a href=""></a><span class="fu">print</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = recoveryTime ~ dosage * dosage2, data = data)

Coefficients:
   (Intercept)          dosage         dosage2  dosage:dosage2  
      51.59815         2.74412        -0.41767         0.06655  </code></pre>
</div>
</div>
</div>
</div></div>
</section>
<section id="hypothesis-testing" class="slide level2">
<h2>Hypothesis testing</h2>
<p><strong>Is there a relationship between the response and the predictor?</strong></p>
<ul>
<li>the calculated <span class="math inline">\(\hat{\alpha}\)</span> and <span class="math inline">\(\hat{\beta}\)</span> are <strong>estimates of the population values</strong> of the intercept and slope and are therefore subject to <strong>sampling variation</strong></li>
<li>their precision is measured by their <strong>estimated standard errors</strong>, <code>e.s.e</code>(<span class="math inline">\(\hat{\alpha}\)</span>) and <code>e.s.e</code>(<span class="math inline">\(\hat{\beta}\)</span>)</li>
<li>these estimated standard errors are used in <strong>hypothesis testing</strong></li>
</ul>
</section>
<section id="hypothesis-testing-1" class="slide level2 smaller">
<h2>Hypothesis testing</h2>
<p><strong>The most common hypothesis test</strong> involves testing the <code>null hypothesis</code> of:</p>
<ul>
<li><span class="math inline">\(H_0:\)</span> There is no relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span></li>
<li>versus the <code>alternative hypothesis</code> <span class="math inline">\(H_a:\)</span> there is some relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span></li>
</ul>
<div class="fragment">
<p><strong>Mathematically</strong>, this corresponds to testing:</p>
<ul>
<li><span class="math inline">\(H_0: \beta=0\)</span></li>
<li>versus <span class="math inline">\(H_a: \beta\neq0\)</span></li>
<li>since if <span class="math inline">\(\beta=0\)</span> then the model <span class="math inline">\(Y_i=\alpha+\beta x_i + \epsilon_i\)</span> reduces to <span class="math inline">\(Y=\alpha + \epsilon_i\)</span></li>
</ul>
</div>
<div class="fragment">
<p><strong>Under the null hypothesis</strong> <span class="math inline">\(H_0: \beta = 0\)</span> <!-- we have: $$\frac{\hat{\beta}-\beta}{e.s.e(\hat{\beta})} \sim t(n-p)$$  --> <img data-src="figures/linear-models/lm-tstatistics.png"></p>
<ul>
<li><span class="math inline">\(n\)</span> is number of observations</li>
<li><span class="math inline">\(p\)</span> is number of model parameters</li>
<li><span class="math inline">\(\frac{\hat{\beta}-\beta}{e.s.e(\hat{\beta})}\)</span> is the ratio of the departure of the estimated value of a parameter, <span class="math inline">\(\hat\beta\)</span>, from its hypothesized value, <span class="math inline">\(\beta\)</span>, to its standard error, called <code>t-statistics</code></li>
<li>the <code>t-statistics</code> follows Student’s t distribution with <span class="math inline">\(n-p\)</span> degrees of freedom</li>
</ul>
</div>
</section>
<section id="hypothesis-testing-2" class="slide level2 smaller">
<h2>Hypothesis testing</h2>
</section>
<section id="hypothesis-testing-3" class="slide level2">
<h2>Hypothesis testing</h2>
<p>Let’s look again at our example data and linear model fitted in R with lm() function.</p>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = recoveryTime ~ dosage, data = data)

Residuals:
   Min     1Q Median     3Q    Max 
-52.97 -39.65  23.19  38.41  56.43 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 28.69540    6.06419   4.732  3.7e-06 ***
dosage      -0.08395    0.98691  -0.085    0.932    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 39.94 on 254 degrees of freedom
Multiple R-squared:  2.849e-05, Adjusted R-squared:  -0.003908 
F-statistic: 0.007236 on 1 and 254 DF,  p-value: 0.9323</code></pre>
</div>
</div>
</div><div class="column" style="width:50%;">

</div></div>
<div class="columns">
<div class="column" style="white-space: normal; word-wrap: break-word; font-size: 60%;">
<ul>
<li><p>Under <em>Estimate</em> we see estimates of our model coefficients, <span class="math inline">\(\hat{\alpha}\)</span> (intercept) and <span class="math inline">\(\hat{\beta}\)</span> (slope, here dosage), followed by their estimated standard errors, <em>Std. Errors</em></p></li>
<li><p>If we were to test if there is an <strong>association between dosage and recovery</strong> we would write under the null hypothesis <span class="math inline">\(H_0: \beta = 0\)</span> <span class="math display">\[\frac{\hat{\beta}-\beta}{e.s.e(\hat{\beta})} = \frac{0.7258-0}{0.5585} = 1.300\]</span></p></li>
</ul>
</div><div class="column" style="white-space: normal; word-wrap: break-word; font-size: 60%;">
<ul>
<li><p>and we would <strong>compare</strong> <em>t-statistics</em> to <em>Student’s t distribution</em> with <span class="math inline">\(n-p = 600 - 2 = 598\)</span> degrees of freedom (as we have 8 observations and two model parameters, <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta\)</span>)</p></li>
<li><p>we can use <strong>Student’s t distribution table</strong> or <strong>R code</strong> to obtain the associated <em>P</em>-value</p></li>
</ul>
<div class="sourceCode" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href=""></a><span class="dv">2</span><span class="sc">*</span><span class="fu">pt</span>(<span class="fl">1.3</span>, <span class="at">df=</span><span class="dv">598</span>, <span class="at">lower=</span>F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1941018</code></pre>
</div>
</div>
</div></div>
<p>here the observed t-statistics is small and therefore yields a relatively large <em>P</em>-value, meaning that <strong>there is not sufficient evidence to reject null hypothesis in favor of the alternative</strong> and conclude that there is not a significant association between dosage and recovery</p>
</section>
<section id="hypothesis-testing-4" class="slide level2">
<h2>Hypothesis testing</h2>
<p>Let’s look again at our example data and linear model fitted in R with lm() function.</p>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = recoveryTime ~ treatment, data = data)

Residuals:
    Min      1Q  Median      3Q     Max 
-17.453  -5.074  -0.115   4.576  17.556 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  66.7465     0.6318   105.6   &lt;2e-16 ***
treatmentB  -78.2654     0.9006   -86.9   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.204 on 254 degrees of freedom
Multiple R-squared:  0.9675,    Adjusted R-squared:  0.9673 
F-statistic:  7552 on 1 and 254 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</div><div class="column" style="width:50%;">

</div></div>
<div class="columns">
<div class="column" style="white-space: normal; word-wrap: break-word; font-size: 60%;">

</div></div>
<p>here the observed t-statistics is small and therefore yields a relatively large <em>P</em>-value, meaning that <strong>there is not sufficient evidence to reject null hypothesis in favor of the alternative</strong> and conclude that there is not a significant association between dosage and recovery</p>
</section>
<section id="vector-matrix-notations" class="slide level2 scrollable smaller">
<h2>Vector-matrix notations</h2>
<p>Let’s <strong>rewrite</strong> our simple linear regression model <span class="math inline">\(Y_i = \alpha + \beta_i + \epsilon_i \quad i=1,\dots n\)</span> <strong>into vector-matrix notation</strong> in <strong>6 steps</strong>.</p>
<div class="fragment">
<p>Step 1. We rename our <span class="math inline">\(\alpha\)</span> to <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta\)</span> to <span class="math inline">\(\beta_1\)</span>.</p>
</div>
<div class="fragment">
<p>Step 2. We notice that we have <span class="math inline">\(n\)</span> equations such as:</p>
<p><span class="math display">\[y_1 = \beta_0 + \beta_1 x_1 + \epsilon_1\]</span> <span class="math display">\[y_2 = \beta_0 + \beta_1 x_2 + \epsilon_2\]</span> <span class="math display">\[y_3 = \beta_0 + \beta_1 x_3 + \epsilon_3\]</span> <span class="math display">\[\dots\]</span> <span class="math display">\[y_n = \beta_0 + \beta_1 x_n + \epsilon_n\]</span></p>
</div>
<div class="fragment">
<p>Step 3. We group all <span class="math inline">\(Y_i\)</span> and <span class="math inline">\(\epsilon_i\)</span> into column vectors: <span class="math inline">\(\mathbf{Y}=\begin{bmatrix} y_1 \\ y_2 \\ \vdots \\ y_{n} \end{bmatrix}\)</span> and <span class="math inline">\(\boldsymbol\epsilon=\begin{bmatrix} \epsilon_1 \\ \epsilon_2 \\ \vdots \\ \epsilon_{n} \end{bmatrix}\)</span></p>
</div>
<div class="fragment">
<p>Step 4. We stack two parameters <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> into another column vector:<span class="math display">\[\boldsymbol\beta=\begin{bmatrix}
  \beta_0  \\
  \beta_1
\end{bmatrix}\]</span></p>
</div>
<div class="fragment">
<p>Step 5. We append a vector of ones with the single predictor for each <span class="math inline">\(i\)</span> and create a matrix with two columns called <strong>design matrix</strong> <span class="math display">\[\mathbf{X}=\begin{bmatrix}
  1 &amp; x_1  \\
  1 &amp; x_2  \\
  \vdots &amp; \vdots \\
  1 &amp; x_{n}
\end{bmatrix}\]</span></p>
</div>
<div class="fragment">
<p>Step 6. We write our linear model in a vector-matrix notations as: <span class="math display">\[\mathbf{Y} = \mathbf{X}\boldsymbol\beta + \boldsymbol\epsilon\]</span></p>
</div>
</section>
<section id="vector-matrix-notations-1" class="slide level2 smaller">
<h2>Vector-matrix notations</h2>
<div id="def-vector-matrix-lm" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 1 (vector matrix form of the linear model)</strong></span> The vector-matrix representation of a linear model with <span class="math inline">\(p-1\)</span> predictors can be written as <span class="math display">\[\mathbf{Y} = \mathbf{X}\boldsymbol\beta + \boldsymbol\epsilon\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(\mathbf{Y}\)</span> is <span class="math inline">\(n \times1\)</span> vector of observations</li>
<li><span class="math inline">\(\mathbf{X}\)</span> is <span class="math inline">\(n \times p\)</span> <strong>design matrix</strong></li>
<li><span class="math inline">\(\boldsymbol\beta\)</span> is <span class="math inline">\(p \times1\)</span> vector of parameters</li>
<li><span class="math inline">\(\boldsymbol\epsilon\)</span> is <span class="math inline">\(n \times1\)</span> vector of vector of random errors, indepedent and identically distributed (i.i.d) N(0, <span class="math inline">\(\sigma^2\)</span>)</li>
</ul>
<p>In full, the above vectors and matrix have the form:</p>
<p><span class="math inline">\(\mathbf{Y}=\begin{bmatrix} y_1 \\ y_2 \\ \vdots \\ y_{n} \end{bmatrix}\)</span> <span class="math inline">\(\boldsymbol\beta=\begin{bmatrix} \beta_0 \\ \beta_1 \\ \vdots \\ \beta_{p} \end{bmatrix}\)</span> <span class="math inline">\(\boldsymbol\epsilon=\begin{bmatrix} \epsilon_1 \\ \epsilon_2 \\ \vdots \\ \epsilon_{n} \end{bmatrix}\)</span> <span class="math inline">\(\mathbf{X}=\begin{bmatrix} 1 &amp; x_{1,1} &amp; \dots &amp; x_{1,p-1} \\ 1 &amp; x_{2,1} &amp; \dots &amp; x_{2,p-1} \\ \vdots &amp; \vdots &amp; \vdots &amp; \vdots \\ 1 &amp; x_{n,1} &amp; \dots &amp; x_{n,p-1} \end{bmatrix}\)</span></p>
</div>
</section>
<section id="vector-matrix-notations-2" class="slide level2">
<h2>Vector-matrix notations</h2>
<div id="thm-lss-vector-matrix" class="theorem">
<p><span class="theorem-title"><strong>Theorem 1 (Least squares in vector-matrix notation)</strong></span> The least squares estimates for a linear regression of the form: <span class="math display">\[\mathbf{Y} = \mathbf{X}\boldsymbol\beta + \boldsymbol\epsilon\]</span></p>
<p>is given by: <span class="math display">\[\hat{\mathbf{\beta}}= (\mathbf{X}^T\mathbf{X})^{-1}\mathbf{X}^T\mathbf{Y}\]</span></p>
</div>
</section>
<section>
<section id="assessing-model-fit" class="title-slide slide level1 center">
<h1>Assessing model fit</h1>
<!-- -   In addition to knowing how to estimate model parameters we need to learn to assess the goodness of fit of a model. -->
<!-- -   We do that by calculating the amount of variability in the response that is explained by the model. -->
</section>
<section id="r2-summary-of-the-fitted-model" class="slide level2">
<h2><span class="math inline">\(R^2\)</span>: summary of the fitted model</h2>
<p><em>TSS</em></p>

<img data-src="session-lm-presentation_files/figure-revealjs/unnamed-chunk-44-1.png" width="576" class="r-stretch"></section>
<section id="r2-summary-of-the-fitted-model-1" class="slide level2">
<h2><span class="math inline">\(R^2\)</span>: summary of the fitted model</h2>
<p><em>TSS</em></p>

<img data-src="session-lm-presentation_files/figure-revealjs/unnamed-chunk-45-1.png" width="576" class="r-stretch"></section>
<section id="r2-summary-of-the-fitted-model-2" class="slide level2">
<h2><span class="math inline">\(R^2\)</span>: summary of the fitted model</h2>
<p><em>TSS</em></p>

<img data-src="session-lm-presentation_files/figure-revealjs/unnamed-chunk-46-1.png" width="576" class="r-stretch"></section>
<section id="r2-summary-of-the-fitted-model-3" class="slide level2">
<h2><span class="math inline">\(R^2\)</span>: summary of the fitted model</h2>
<p><em>RSS</em></p>

<img data-src="session-lm-presentation_files/figure-revealjs/unnamed-chunk-47-1.png" width="576" class="r-stretch"></section>
<section id="r2-summary-of-the-fitted-model-4" class="slide level2">
<h2><span class="math inline">\(R^2\)</span>: summary of the fitted model</h2>
<p><em>RSS</em></p>

<img data-src="session-lm-presentation_files/figure-revealjs/unnamed-chunk-48-1.png" width="576" class="r-stretch"></section>
<section id="r2-summary-of-the-fitted-model-5" class="slide level2">
<h2><span class="math inline">\(R^2\)</span>: summary of the fitted model</h2>
<p><em>RSS</em></p>

<img data-src="session-lm-presentation_files/figure-revealjs/unnamed-chunk-49-1.png" width="576" class="r-stretch"></section>
<section id="r2-summary-of-the-fitted-model-6" class="slide level2">
<h2><span class="math inline">\(R^2\)</span>: summary of the fitted model</h2>
<div class="columns">
<div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="session-lm-presentation_files/figure-revealjs/unnamed-chunk-50-1.png" width="768"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:60%;">
<p><br></p>
<ul>
<li><p><strong>TSS</strong>, denoted <strong>Total corrected sum-of-squares</strong> is the residual sum-of-squares for Model 0 <span class="math display">\[S(\hat{\beta_0}) = TSS = \sum_{i=1}^{n}(y_i - \bar{y})^2 = S_{yy}\]</span> corresponding the to the sum of squared distances to the purple line</p></li>
<li><p><strong>RSS</strong>, the residual sum-of-squares, is defined as: <span class="math display">\[RSS = \displaystyle \sum_{i=1}^{n}(y_i - \{\hat{\beta_0} + \hat{\beta}_1x_{1i} + \dots + \hat{\beta}_px_{pi}\}) = \sum_{i=1}^{n}(y_i - \hat{y_i})^2\]</span> and corresponds to the squared distances between the observed values <span class="math inline">\(y_i, \dots,y_n\)</span> to fitted values <span class="math inline">\(\hat{y_1}, \dots \hat{y_n}\)</span>, i.e.&nbsp;distances to the red fitted line</p></li>
</ul>
</div></div>
</section>
<section id="r2-summary-of-the-fitted-model-7" class="slide level2">
<h2><span class="math inline">\(R^2\)</span>: summary of the fitted model</h2>
<div class="columns">
<div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="session-lm-presentation_files/figure-revealjs/unnamed-chunk-51-1.png" width="768"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:60%;">
<p><br></p>
<div id="def-r2" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 2 (<span class="math inline">\(R^2\)</span>)</strong></span> A simple but useful measure of model fit is given by <span class="math display">\[R^2 = 1 - \frac{RSS}{TSS}\]</span> where:</p>
<ul>
<li>RSS is the residual sum-of-squares for Model 1, the fitted model of interest</li>
<li>TSS is the sum of squares of the <strong>null model</strong></li>
<li><span class="math inline">\(R^2\)</span> is also referred as <strong>coefficient of determination</strong></li>
<li><span class="math inline">\(R^2\)</span> is expressed on a scale, as a proportion between 0 and 1 of the total variation in the data.</li>
</ul>
</div>
</div></div>
<!-- ## $R^2$: summary of the fitted model -->
<!-- ::: incremental -->
<!-- -   $R^2$ quantifies how much of a drop in the residual sum-of-squares is accounted for by fitting the proposed model -->
<!-- -   $R^2$ is also referred as **coefficient of determination** -->
<!-- -   It is expressed on a scale, as a proportion (between 0 and 1) of the total variation in the data -->
<!-- -   Values of $R^2$ approaching 1 indicate the model to be a good fit -->
<!-- -   Values of $R^2$ less than 0.5 suggest that the model gives rather a poor fit to the data -->
<!-- ::: -->
</section>
<section id="r2-and-correlation-coefficient" class="slide level2">
<h2><span class="math inline">\(R^2\)</span> and correlation coefficient</h2>
<div class="fragment">
<div id="thm-r2" class="theorem">
<p><span class="theorem-title"><strong>Theorem 2 (<span class="math inline">\(R^2\)</span>)</strong></span> In the case of simple linear regression:</p>
<p>Model 1: <span class="math inline">\(Y_i = \beta_0 + \beta_1x + \epsilon_i\)</span> <span class="math display">\[R^2 = r^2\]</span> where:</p>
<ul>
<li><span class="math inline">\(R^2\)</span> is the coefficient of determination</li>
<li><span class="math inline">\(r^2\)</span> is the sample correlation coefficient</li>
</ul>
</div>
</div>
</section>
<section id="r2adj" class="slide level2">
<h2><span class="math inline">\(R^2(adj)\)</span></h2>
<div>
<ul>
<li class="fragment">In the case of multiple linear regression we are using the <strong>adjusted version of</strong> <span class="math inline">\(R^2\)</span> to assess the model fit as the number of explanatory variables increase, <span class="math inline">\(R^2\)</span> also increases.</li>
</ul>
</div>
<div class="fragment">
<div id="thm-r2adj" class="theorem">
<p><span class="theorem-title"><strong>Theorem 3 (<span class="math inline">\(R^2(adj)\)</span>)</strong></span> For any multiple linear regression <span class="math display">\[Y_i = \beta_0 + \beta_1x_{1i} + \dots + \beta_{p-1}x_{(p-1)i} +  \epsilon_i\]</span> <span class="math inline">\(R^2(adj)\)</span> is defined as <span class="math display">\[R^2(adj) = 1-\frac{\frac{RSS}{n-p-1}}{\frac{TSS}{n-1}}\]</span></p>
<ul>
<li><span class="math inline">\(p\)</span> is the number of independent predictors, i.e.&nbsp;the number of variables in the model, excluding the constant and <span class="math inline">\(n\)</span> is number of observations.</li>
</ul>
<p><span class="math inline">\(R^2(adj)\)</span> can also be calculated from <span class="math inline">\(R^2\)</span>: <span class="math display">\[R^2(adj) = 1 - (1-R^2)\frac{n-1}{n-p-1}\]</span></p>
</div>
<!-- ## $R^2$ -->
<!-- *Live demo* -->
<!-- ``` r -->
<!-- htwtgen <- read.csv("data/lm/heights_weights_gender.csv") -->
<!-- head(htwtgen) -->
<!-- attach(htwtgen) -->
<!-- ## Simple linear regression -->
<!-- model.simple <- lm(Height ~ Weight, data=htwtgen) -->
<!-- # TSS -->
<!-- TSS <- sum((Height - mean(Height))^2) -->
<!-- # RSS -->
<!-- # residuals are returned in the model type names(model.simple) -->
<!-- RSS <- sum((model.simple$residuals)^2) -->
<!-- R2 <- 1 - (RSS/TSS) -->
<!-- print(R2) -->
<!-- print(summary(model.simple)) -->
<!-- ``` -->
<!-- ## $R^2$ -->
<!-- *Live demo* -->
<!-- ``` r -->
<!-- htwtgen <- read.csv("data/lm/heights_weights_gender.csv") -->
<!-- head(htwtgen) -->
<!-- attach(htwtgen) -->
<!-- ## Multiple regression -->
<!-- model.multiple <- lm(Height ~ Weight + Gender, data=htwtgen) -->
<!-- n <- length(Weight) -->
<!-- p <- 1 -->
<!-- RSS <- sum((model.multiple$residuals)^2) -->
<!-- R2_adj <- 1 - (RSS/(n-p-1))/(TSS/(n-1)) -->
<!-- print(R2_adj) -->
<!-- print(summary(model.multiple)) -->
<!-- ``` -->
</div>
</section></section>
<section>
<section id="checking-model-assumptions" class="title-slide slide level1 center">
<h1>Checking model assumptions</h1>

</section>
<section id="the-assumptions-of-a-linear-model" class="slide level2">
<h2>The assumptions of a linear model</h2>
<div>
<ul>
<li class="fragment">Before making use of a fitted model for explanation or prediction, it is wise to check that the model provides an adequate description of the data.</li>
<li class="fragment">Informally we have been using box plots and scatter plots to look at the data.</li>
<li class="fragment">There are however formal assumptions that should be met when fitting linear models.</li>
</ul>
</div>
</section>
<section id="the-assumptions-of-a-linear-model-1" class="slide level2">
<h2>The assumptions of a linear model</h2>
<div class="fragment">
<p><br></p>
<p><strong>Linearity:</strong></p>
<ul>
<li>The relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> is linear</li>
</ul>
</div>
<div class="fragment">
<p><strong>Independence of errors</strong></p>
<ul>
<li><span class="math inline">\(Y\)</span> is independent of errors, there is no relationship between the residuals and <span class="math inline">\(Y\)</span></li>
</ul>
</div>
<div class="fragment">
<p><strong>Normality of errors</strong></p>
<ul>
<li>The residuals must be approximately normally distributed</li>
</ul>
</div>
<div class="fragment">
<p><strong>Equal variances</strong></p>
<ul>
<li>The variance of the residuals is the same for all values of <span class="math inline">\(X\)</span></li>
</ul>
</div>
</section>
<section id="checking-assumptions" class="slide level2 smaller">
<h2>Checking assumptions</h2>
<p><strong>Residuals</strong>, <span class="math inline">\(\hat{\epsilon_i} = y_i - \hat{y_i}\)</span> are the <strong>main ingredient to check model assumptions</strong>.</p>
<div class="fragment">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="session-lm-presentation_files/figure-revealjs/unnamed-chunk-52-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="checking-assumptions-1" class="slide level2 smaller">
<h2>Checking assumptions</h2>
<p><strong>Residuals</strong>, <span class="math inline">\(\hat{\epsilon_i} = y_i - \hat{y_i}\)</span> are the <strong>main ingredient to check model assumptions</strong>.</p>
<div class="fragment">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="session-lm-presentation_files/figure-revealjs/unnamed-chunk-53-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="evaluating-linear-models" class="slide level2">
<h2>Evaluating linear models</h2>
<p><br></p>
<p>Regression models can be evaluated by assessing a model fit or by directly evaluating the prediction error via using data splitting strategies.</p>
<div class="fragment">
<div class="columns">
<div class="column" style="width:55%;">
<p><strong>Model fit</strong></p>
<p><strong>Adjusted R-squared</strong> <span class="math display">\[R_{adj}^2=1-\frac{RSS}{TSS}\frac{n-1}{n-p-1}\]</span></p>
<p><strong>Akaike information criterion (AIC)</strong> <span class="math display">\[\text{AIC} = n \ln(\text{RSS}/n) + 2p\]</span></p>
<p><strong>Bayesian information criterion (BIC)</strong> <span class="math display">\[\text{BIC} = n \ln(\text{RSS}/n) + p \ln(n)\]</span></p>
</div><div class="column" style="width:5%;">

</div><div class="column" style="width:40%;">
<p><strong>Prediction error</strong></p>
<p><strong>Mean Squared Error (MSE)</strong> <span class="math display">\[MSE = \frac{1}{N}\sum_{i=1}^{N}({y_i}-\hat{y}_i)^2\]</span> <strong>Root Mean Squared Error (RMSE)</strong> <span class="math display">\[RMSE = \sqrt{\frac{1}{N}\sum_{i=1}^{N}({y_i}-\hat{y}_i)^2}\]</span></p>
<p><strong>Mean Absolute Error (MAE)</strong> <span class="math display">\[MAE = \frac{1}{N}\sum_{i=1}^{N}|{y_i}-\hat{y}_i|\]</span></p>
</div></div>
</div>
</section>
<section id="faq" class="slide level2">
<h2>FAQ</h2>
<div class="columns">
<div class="column" style="font-size: 65%;">
<p>Is linear regression only for normally distributed data?<br>
<strong>Short answer:</strong> No, not exactly.<br>
<strong>What matters:</strong><br>
- <strong>The errors (residuals)</strong> should be approximately normally distributed, <strong>not the predictors or outcome</strong>.<br>
- Normality is mainly needed for <strong>valid p-values and confidence intervals</strong>, not for estimating coefficients.</p>
<hr>
<p>Can I use categorical variables in linear regression?<br>
<strong>Yes.</strong><br>
R automatically converts categorical variables into <strong>dummy variables (0/1)</strong> behind the scenes.<br>
Interpret carefully, especially with interactions!</p>
<hr>
<p>Why is multicollinearity a problem?<br>
Because it inflates <strong>standard errors</strong>, making it harder to tell which predictor matters.<br>
Coefficients may still be accurate for <strong>prediction</strong>, but <strong>interpretation becomes unstable</strong>.</p>
<hr>
<p>Is a low p-value always a sign of a good predictor?<br>
<strong>No.</strong><br>
A variable can have a low p-value due to <strong>sample size</strong>, <strong>correlation with other variables</strong>, or <strong>data quirks</strong>.<br>
Always combine p-values with <strong>effect size</strong>, <strong>context</strong>, and <strong>visual inspection</strong>.</p>
</div><div class="column" style="font-size: 65%;">
<p>Why residuals look curved. Is that a problem?<br>
<strong>Yes.</strong> Curved residuals suggest <strong>non-linearity</strong>.<br>
Try transforming variables or using models like <strong>polynomial regression</strong>, <strong>splines</strong>, or <strong>generalized additive models (GAMs)</strong>.</p>
<hr>
<p>Should I use <span class="math inline">\(R^2\)</span> to compare models?<br>
<strong>Not always.</strong><br>
- <span class="math inline">\(R^2\)</span> always increases with more predictors. - Use <strong>adjusted R²</strong>, <strong>AIC</strong>, or <strong>cross-validation</strong> for better model comparison.</p>
<hr>
<p>Does significant interaction mean both main effects must be significant too?<br>
<strong>No.</strong><br>
An interaction can be significant even if the main effects are not.<br>
Interactions test if <strong>the effect of one variable depends on another</strong>, not their individual impact.</p>
<hr>
<p>Can linear regression be used to fit a non-linear line?<br>
<strong>Short answer:</strong> Yes and No.<br>
You can transform your variables making them linear. Then in the original space,the fitted line will be non-linear. However the fitted line in the transformed space is still linear. Linear models assume a linear relationship between the outcome and predictors, meaning they fit a straight line (in 2D), a plane (in 3D), or a hyperplane in higher dimensions.</p>
</div></div>
</section></section>
<section id="exercises" class="title-slide slide level1 center">
<h1>Exercises</h1>
<p>Let’s practice in exercises fitting linear models, hypothesis testing and assessing model fit.</p>
</section>

<section>
<section id="feature-selection" class="title-slide slide level1 center">
<h1>Feature selection</h1>
<p><em>Group discussion</em> <br></p>
<p>It is time to try to find the best model to explain <code>BMI</code> using <code>diabetes</code> data. Given from what we have learnt so far about linear regression models, how would you find the best model?</p>
<p>As a reminder, we have below variables in the data:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> [1] "id"       "chol"     "stab.glu" "hdl"      "ratio"    "glyhb"   
 [7] "location" "age"      "gender"   "height"   "weight"   "frame"   
[13] "bp.1s"    "bp.1d"    "bp.2s"    "bp.2d"    "waist"    "hip"     
[19] "time.ppn" "BMI"      "obese"    "diabetic"</code></pre>
</div>
</div>
</section>
<section id="feature-selection-1" class="slide level2">
<h2>Feature selection</h2>
<p><em>Definition</em> <br></p>
<p>Feature selection is the process of selecting the most relevant and informative subset of features from a larger set of potential features in order to improve the performance and interpretability of a machine learning model.</p>
<h3 id="there-are-generally-three-main-groups-of-feature-selection-methods">There are generally three main groups of feature selection methods:</h3>
<div>
<ul>
<li class="fragment"><strong>Filter methods</strong> use statistical measures to score the features and select the most relevant ones, e.g.&nbsp;based on correlation coefficient. Computationally efficient but may overlook complex interactions between features.</li>
<li class="fragment"><strong>Wrapper methods</strong> use ML algorithm to evaluate the performance of different subsets of features, e.g.&nbsp;forward/backward feature selection. Computationally heavy.</li>
<li class="fragment"><strong>Embedded methods</strong> incorporate feature selection as part of the ML algorithm itself, e.g.&nbsp;<strong>regularized regression</strong> or <strong>Random Forest</strong>. These methods are computationally efficient and can be more accurate than filter methods.</li>
</ul>
</div>
</section>
<section id="regularized-regression" class="slide level2">
<h2>Regularized regression</h2>
<p><em>definition</em> <br></p>
<div>
<ul>
<li class="fragment">Regularized regression expands on the regression by adding a <strong>penalty term(s)</strong> to <strong>shrink the model coefficients</strong> of less important features towards zero.</li>
<li class="fragment">This can help to prevent overfitting and improve the accuracy of the predictive model.</li>
<li class="fragment">Depending on the penalty added, we talk about <strong>Ridge</strong>, <strong>Lasso</strong> or <strong>Elastic Nets regression</strong>.</li>
</ul>
</div>
</section>
<section id="regularized-regression-1" class="slide level2">
<h2>Regularized regression</h2>
<p><em>Ridge regression</em> <br></p>
<ul>
<li>Previously we saw that the least squares fitting procedure estimates model coefficients <span class="math inline">\(\beta_0, \beta_1, \cdots, \beta_p\)</span> using the values that minimize the residual sum of squares: <span class="math display">\[RSS = \sum_{i=1}^{n} \left( y_i - \beta_0 - \sum_{j=1}^{p}\beta_jx_{ij} \right)^2\]</span></li>
</ul>
<div class="fragment">
<ul>
<li>In <strong>regularized regression</strong> the coefficients are estimated by minimizing slightly different quantity. Specifically, in <strong>Ridge regression</strong> we estimate <span class="math inline">\(\hat\beta^{L}\)</span> that minimizes <span id="eq-ridge"><span class="math display">\[\sum_{i=1}^{n} \left( y_i - \beta_0 - \sum_{j=1}^{p}\beta_jx_{ij} \right)^2 + \lambda \sum_{j=1}^{p}\beta_j^2 = RSS + \lambda \sum_{j=1}^{p}\beta_j^2 \qquad(2)\]</span></span></li>
</ul>
<p>where:</p>
<p><span class="math inline">\(\lambda \ge 0\)</span> is a <strong>tuning parameter</strong> to be determined separately e.g.&nbsp;via cross-validation</p>
</div>
</section>
<section id="regularized-regression-2" class="slide level2">
<h2>Regularized regression</h2>
<p><em>Ridge regression</em> <br></p>
<p><span class="math display">\[\sum_{i=1}^{n} \left( y_i - \beta_0 - \sum_{j=1}^{p}\beta_jx_{ij} \right)^2 + \lambda \sum_{j=1}^{p}\beta_j^2 = RSS + \lambda \sum_{j=1}^{p}\beta_j^2\]</span></p>
<p><a href="#/eq-ridge" class="quarto-xref">Equation&nbsp;2</a> trades two different criteria:</p>
<ul>
<li>lasso regression seeks coefficient estimates that fit the data well, by making RSS small</li>
<li>however, the second term <span class="math inline">\(\lambda \sum_{j=1}^{p}\beta_j^2\)</span>, called <strong>shrinkage penalty</strong> is small when <span class="math inline">\(\beta_1, \cdots, \beta_p\)</span> are close to zero, so it has the effect of <strong>shrinking</strong> the estimates of <span class="math inline">\(\beta_j\)</span> towards zero.</li>
<li>the tuning parameter <span class="math inline">\(\lambda\)</span> controls the relative impact of these two terms on the regression coefficient estimates
<ul>
<li>when <span class="math inline">\(\lambda = 0\)</span>, the penalty term has no effect</li>
<li>as <span class="math inline">\(\lambda \rightarrow \infty\)</span> the impact of the shrinkage penalty grows and the ridge regression coefficient estimates approach zero</li>
</ul></li>
</ul>
</section>
<section id="regularized-regression-3" class="slide level2">
<h2>Regularized regression</h2>
<p><em>Ridge regression</em> <br></p>

<img data-src="session-lm-presentation_files/figure-revealjs/ridge-run-1.png" class="margin-caption r-stretch quarto-figure-center" width="960"><p class="caption">Example of Ridge regression to model BMI using age, chol, hdl and glucose variables: model coefficients are plotted over a range of lambda values, showing how initially for small lambda values all variables are part of the model and how they gradually shrink towards zero for larger lambda values.</p></section>
<section id="bias-variance-trade-off" class="slide level2">
<h2>Bias-variance trade-off</h2>
<p><br></p>
<p>Ridge regression’s advantages over least squares estimates stems from <strong>bias-variance trade-off</strong></p>
<div>
<ul>
<li class="fragment">The bias-variance trade-off describes the relationship between model complexity, prediction accuracy, and the ability of the model to generalize to new data.</li>
<li class="fragment"><strong>Bias</strong> refers to the error that is introduced by approximating a real-life problem with a simplified model
<ul>
<li class="fragment">e.g.&nbsp;a high bias model is one that makes overly simplistic assumptions about the underlying data, resulting in <em>under-fitting</em> and poor accuracy.</li>
</ul></li>
<li class="fragment"><strong>Variance</strong> refers to the sensitivity of a model to fluctuations in the training data.
<ul>
<li class="fragment">e.g.&nbsp;a high variance model is one that is overly complex and captures noise in the training data, resulting in <em>overfitting</em> and poor generalization to new data.</li>
</ul></li>
</ul>
</div>
</section>
<section id="bias-variance-trade-off-1" class="slide level2">
<h2>Bias-variance trade-off</h2>
<p><br></p>
<p>The goal of machine learning is to find a model with <strong>the right balance between bias and variance</strong>.</p>
<div>
<ul>
<li class="fragment">The bias-variance trade-off can be visualized in terms of MSE, means squared error of the model. The <strong>MSE</strong> can be decomposed into: <span class="math display">\[MSE(\hat\beta) := bias^2(\hat\beta) + Var(\hat\beta) + noise\]</span>
<ul>
<li class="fragment">The irreducible error is the inherent noise in the data that cannot be reduced by any model</li>
<li class="fragment">The bias and variance terms can be reduced by choosing an appropriate model complexity.</li>
<li class="fragment">The trade-off lies in finding the right balance between bias and variance that minimizes the total MSE.</li>
</ul></li>
<li class="fragment">In practice, this trade-off can be addressed by <strong>regularizing the model</strong>, selecting an appropriate model complexity, or by using ensemble methods that combine multiple models to reduce the variance.</li>
</ul>
</div>
</section>
<section id="bias-variance-trade-off-2" class="slide level2">
<h2>Bias-variance trade-off</h2>
<p><br></p>

<img data-src="images/bias-variance.png" class="quarto-figure quarto-figure-center r-stretch" style="width:100.0%" id="fig-bias-variance"><p class="caption">
Figure&nbsp;1: Squared bias, variance and test mean squared error for ridge regression predictions on a simulated data as a function of lambda demonstrating bias-variance trade-off. Based on Gareth James et. al, A Introduction to statistical learning
</p></section>
<section id="ridge-vs.-lasso" class="slide level2">
<h2>Ridge vs.&nbsp;Lasso</h2>
<p>In <strong>Ridge</strong> regression we minimize: <span id="eq-ridge2"><span class="math display">\[\sum_{i=1}^{n} \left( y_i - \beta_0 - \sum_{j=1}^{p}\beta_jx_{ij} \right)^2 + \lambda \sum_{j=1}^{p}\beta_j^2 = RSS + \lambda \sum_{j=1}^{p}\beta_j^2 \qquad(3)\]</span></span> where <span class="math inline">\(\lambda \sum_{j=1}^{p}\beta_j^2\)</span> is also known as <strong>L2</strong> regularization element or <span class="math inline">\(l_2\)</span> penalty</p>
<p>In <strong>Lasso</strong> regression, that is Least Absolute Shrinkage and Selection Operator regression we change penalty term to absolute value of the regression coefficients: <span id="eq-lasso"><span class="math display">\[\sum_{i=1}^{n} \left( y_i - \beta_0 - \sum_{j=1}^{p}\beta_jx_{ij} \right)^2 + \lambda \sum_{j=1}^{p}|\beta_j| = RSS + \lambda \sum_{j=1}^{p}|\beta_j| \qquad(4)\]</span></span> where <span class="math inline">\(\lambda \sum_{j=1}^{p}|\beta_j|\)</span> is also known as <strong>L1</strong> regularization element or <span class="math inline">\(l_1\)</span> penalty</p>
<p>Lasso regression was introduced to help model interpretation. With Ridge regression we improve model performance but unless <span class="math inline">\(\lambda = \infty\)</span> all beta coefficients are non-zero, hence all variables remain in the model. By using <span class="math inline">\(l_1\)</span> penalty we can force some of the coefficients estimates to be exactly equal to 0, hence perform <strong>variable selection</strong></p>
</section>
<section id="ridge-vs.-lasso-1" class="slide level2">
<h2>Ridge vs.&nbsp;Lasso</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="session-lm-presentation_files/figure-revealjs/ridge-run-02-1.png" width="960"></p>
<figcaption>Example of Ridge regression to model BMI using age, chol, hdl and glucose variables: model coefficients are plotted over a range of lambda values, showing how initially for small lambda values all variables are part of the model and how they gradually shrink towards zero for larger lambda values.</figcaption>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="session-lm-presentation_files/figure-revealjs/lasso-run-1.png" width="960"></p>
<figcaption>Example of Lasso regression to model BMI using age, chol, hdl and glucose variables: model coefficients are plotted over a range of lambda values, showing how initially for small lambda values all variables are part of the model and how they gradually shrink towards zero and are also set to zero for larger lambda values.</figcaption>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="elastic-net" class="slide level2">
<h2>Elastic Net</h2>
<p><br></p>
<p><strong>Elastic Net</strong> use both L1 and L2 penalties to try to find middle grounds by performing parameter shrinkage and variable selection. <span id="eq-elastic-net"><span class="math display">\[\sum_{i=1}^{n} \left( y_i - \beta_0 - \sum_{j=1}^{p}\beta_jx_{ij} \right)^2 + \lambda \sum_{j=1}^{p}|\beta_j| + \lambda \sum_{j=1}^{p}\beta_j^2 = RSS + \lambda \sum_{j=1}^{p}|\beta_j| + \lambda \sum_{j=1}^{p}\beta_j^2  \qquad(5)\]</span></span></p>

<img data-src="session-lm-presentation_files/figure-revealjs/elastic-net-1.png" class="margin-caption r-stretch quarto-figure-center" width="960"><p class="caption">Example of Elastic Net regression to model BMI using age, chol, hdl and glucose variables: model coefficients are plotted over a range of lambda values and alpha value 0.1, showing the changes of model coefficients as a function of lambda being somewhere between those for Ridge and Lasso regression.</p></section>
<section id="elastic-net-1" class="slide level2">
<h2>Elastic Net</h2>
<p><em>In R with <code>glmnet</code></em> <br></p>
<p>In the <code>glmnet</code> library we can fit Elastic Net by setting parameters <span class="math inline">\(\alpha\)</span>. Under the hood <code>glmnet</code> minimizes a cost function: <span class="math display">\[\sum_{i_=1}^{n}(y_i-\hat y_i)^2 + \lambda \left ( (1-\alpha) \sum_{j=1}^{p}\beta_j^2 + \alpha \sum_{j=1}^{p}|\beta_j|\right )\]</span> where:</p>
<ul>
<li><span class="math inline">\(n\)</span> is the number of samples</li>
<li><span class="math inline">\(p\)</span> is the number of parameters</li>
<li><span class="math inline">\(\lambda\)</span>, <span class="math inline">\(\alpha\)</span> hyperparameters control the shrinkage</li>
</ul>
<p>When <span class="math inline">\(\alpha = 0\)</span> this corresponds to Ridge regression and when <span class="math inline">\(\alpha=1\)</span> this corresponds to Lasso regression. A value of <span class="math inline">\(0 &lt; \alpha &lt; 1\)</span> gives us <strong>Elastic Net regularization</strong>, combining both L1 and L2 regularization terms.</p>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="session-lm-presentation_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="session-lm-presentation_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="session-lm-presentation_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="session-lm-presentation_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="session-lm-presentation_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="session-lm-presentation_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="session-lm-presentation_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="session-lm-presentation_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="session-lm-presentation_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="session-lm-presentation_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="session-lm-presentation_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Copied!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Copied!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp('/' + window.location.host + '/');
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>
    

</body></html>