project:
  type: book
  output-dir: docs
    

book:
  title: "Common steps"
  author: "Olga Dethlefsen"
  #date: "8/31/2022"
  chapters:
    - index.qmd
    #- intro.qmd
    - case-study-base-r-cls.qmd

bibliography: references.bib

format:
  html:
    self-contained: false
    theme: cosmo
    code-fold: true
      
  # pdf:
  #   documentclass: scrreprt



