<!DOCTYPE html>
<html lang="en"><head>
<script src="presentation_files/libs/clipboard/clipboard.min.js"></script>
<script src="presentation_files/libs/quarto-html/tabby.min.js"></script>
<script src="presentation_files/libs/quarto-html/popper.min.js"></script>
<script src="presentation_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="presentation_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="presentation_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="presentation_files/libs/quarto-html/quarto-syntax-highlighting-01c78b5cd655e4cd89133cf59d535862.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.6.36">

  <title>Survival Analysis</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="presentation_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="presentation_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="presentation_files/libs/revealjs/dist/theme/quarto-14d72de84f06f2b03b4ce964173f34e2.css">
  <link href="presentation_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="presentation_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="presentation_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="presentation_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="presentation_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="presentation_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Survival Analysis</h1>

<div class="quarto-title-authors">
</div>

</section>
<section id="survival-analysis" class="slide level2 smaller">
<h2>Survival analysis 🏕️</h2>
<p><br></p>
<p>Statistical methods for <strong>time-to-event data</strong></p>
<ul>
<li>Originally applied to time until death in 17th-century mortality studies</li>
<li>Now widely used in various fields:
<ul>
<li>Medicine (e.g., time to relapse)</li>
<li>Marketing (e.g., time to next purchase)</li>
<li>Engineering (e.g., time to failure)</li>
<li>Criminology (e.g., time to reoffend)</li>
</ul></li>
</ul>
<div class="fragment">
<p><br></p>
<p>Survival analysis is <strong>not limited to studying time-based events</strong>.</p>
<ul>
<li>We can study the number of treatment sessions until a patient recovers</li>
<li>or the number of attempts until a student passes an exam.</li>
<li>Common feature: <strong>censored data</strong></li>
</ul>
</div>
</section>
<section id="survival-and-censoring-times" class="slide level2 smaller">
<h2>Survival and censoring times</h2>
<div class="fragment">
<p><br></p>
<p>Let’s imagine:</p>
<ul>
<li>a mortality study of terminally ill patients receiving a medical treatment.</li>
<li>We follow a group of patients over <strong>24 months follow-up period</strong></li>
<li>and record the <strong>time until death</strong> or <strong>until the end of the study</strong>.</li>
</ul>
<p><br></p>
</div>
<div class="fragment">
<p>For each patient, we suppose there is:</p>
<ul>
<li>a true <strong>survival time</strong> <span class="math inline">\(T\)</span>
<ul>
<li>representing the time at which the event of interest occurs (here death)</li>
</ul></li>
<li>a <strong>censoring time</strong> <span class="math inline">\(C\)</span>
<ul>
<li>representing the time at which the patient is lost to follow-up or the study ends.</li>
</ul></li>
</ul>
<p><br></p>
</div>
<div class="fragment">
<p>We observe the <strong>random variable</strong> <span class="math display">\[Y = min (T, C)\]</span></p>
<ul>
<li>If the event occurs before censoring (i.e.&nbsp;<span class="math inline">\(T &lt; C\)</span>) then we observe the true survival time <span class="math inline">\(T\)</span>.</li>
<li>Otherwise, if censoring occurs before the event (i.e.&nbsp;<span class="math inline">\(T &gt; C\)</span>), we observe the censoring time <span class="math inline">\(C\)</span>.</li>
</ul>
<p>We also observe a <strong>status indicator</strong></p>
<p><span class="math display">\[\begin{equation}
    \sigma =
    \left\{
        \begin{array}{cc}
                1 &amp; \mathrm{if\ } T \le C \\
                0 &amp; \mathrm{if\ } T&gt;C \\
        \end{array}
    \right.
\end{equation}\]</span></p>
</div>
</section>
<section id="survival-and-censoring-times-1" class="slide level2 smaller">
<h2>Survival and censoring times</h2>

<img data-src="presentation_files/figure-revealjs/fig-censoring-1.png" width="960" class="r-stretch quarto-figure-center" id="fig-censoring"><p class="caption">
Figure&nbsp;1: Example of right-censored data in a mortatily study lasting 24 months. The horizontal lines represent the time to event or censoring for each patient. The points indicate whether the event occurred (event) or not (censored).
</p><div class="fragment">
<div>
<ul>
<li class="fragment">for P1 we get <span class="math inline">\((y_1= t_1, \space \sigma_1 = 1)\)</span> since we observe event (death) as ca. 23 months, before the end of the follow-up at 24 months.</li>
<li class="fragment">for P2 we get <span class="math inline">\((y_2= c_1, \space \sigma_1 = 0)\)</span> since the patient is still alive at the end of the study at 24 months, meaning that the patient has survied at least 24 months (censored)</li>
<li class="fragment">for P4, we get <span class="math inline">\((y_4= c_4, \space \sigma_4 = 0)\)</span>, anther censored data point. The study is not over yet, the patient has not diet but is <strong>lost to follow-up</strong>, e.g.&nbsp;due to withdrawing from the study</li>
</ul>
</div>
</div>
</section>
<section id="independent-censoring" class="slide level2 smaller">
<h2>Independent Censoring</h2>
<p><em>Assumptions</em></p>
<p><br></p>
<div class="fragment">
<p>To analyze survival data correctly, we must assume:</p>
<ul>
<li><strong>Censoring is independent</strong> of the event process</li>
<li>i.e.&nbsp;the <strong>reason for censoring is unrelated</strong> to the risk of the event</li>
<li>Censored individuals are assumed to have the <strong>same event probability</strong> as those still under observation</li>
</ul>
</div>
<div class="fragment">
<p><br></p>
<p><strong>Example</strong></p>
<ul>
<li>✅ <strong>Valid</strong>: Patients leave a cancer study for unrelated reasons (e.g., moving away)</li>
<li>❌ <strong>Violation</strong>: Patients drop out because they are very sick (higher event risk)</li>
</ul>
</div>
</section>
<section id="left-and-interval-censoring" class="slide level2">
<h2>Left and interval censoring</h2>

<img data-src="presentation_files/figure-revealjs/fig-left-interval-1.png" width="960" class="r-stretch quarto-figure-center" id="fig-left-interval"><p class="caption">
Figure&nbsp;2: Example of left and interval censoring in an age study. Left-censored patients were diagnosed before the study, and interval-censored patients were diagnosed between visits.
</p></section>
<section id="kaplan-meier-estimator" class="slide level2 smaller">
<h2>Kaplan-Meier estimator</h2>
<p><br></p>
<p>The <strong>survival curve</strong>, or survival function, is a decreasing function that quantifies the probability of surviving past time <span class="math inline">\(t\)</span> and is defined as <span id="eq-surv"><span class="math display">\[S(t) = Pr(T &gt; t) \qquad(1)\]</span></span></p>
<p><br></p>
<p>The <strong>Kaplan-Meier (KM) estimator</strong> is a non-parametric statistic used to estimate the survival function from lifetime data and is given by: <span id="eq-KM"><span class="math display">\[\hat{S}(t) = \prod_{j=1}^{t} \left( 1 - \frac{d_j}{n_j} \right) \qquad(2)\]</span></span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(d_j\)</span>: number of failures at time <span class="math inline">\(t_j\)</span></li>
<li><span class="math inline">\(n_j\)</span>: number of patients at risk just before time <span class="math inline">\(t_ij\)</span></li>
<li>and the product is taken over all time intervals in which a death occurred, up to and including <span class="math inline">\(t\)</span></li>
</ul>
<p>Kapalan-Meier estimator is also known as <strong>product-limit</strong> estimator.</p>
</section>
<section id="kaplan-meier-estimator-1" class="slide level2 smaller">
<h2>Kaplan-Meier estimator</h2>
<p><em>Tooth filling example</em></p>
<div class="columns">
<div class="column" style="width:35%;">
<p>Suppose we have 10 patients who receive a tooth filling, and we want to track how long these fillings last before they fail. The failure times (in months) for each patient are recorded:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   10 obs. of  3 variables:
 $ patientID: int  1 2 3 4 5 6 7 8 9 10
 $ time     : num  10 8 11 5 4 3 7 6 12 8
 $ surv     : num  1 1 1 1 1 1 1 1 1 1</code></pre>
</div>
</div>
<p>To calculate the Kaplan-Meier Curve:</p>
<ol type="1">
<li>We <strong>sort</strong> the data by time to failure.2.</li>
<li>For each time, we calculate the <strong>survival probabilities</strong>, i.e.&nbsp;the probability the filling lasting beyond that time.</li>
<li>We apply the Kaplan-Meier formula <span class="math display">\[\hat{S}(t) = \prod_{j=1}^{t} \left( 1 - \frac{d_j}{n_j} \right)\]</span> to calculate the probability of surviving up to time <span class="math inline">\(t\)</span>, as the product of all individual survival probabilities at each time up to <span class="math inline">\(t\)</span>:</li>
</ol>
</div><div class="column" style="width:5%;">

</div><div class="column" style="width:60%;">
<table class="caption-top">
<colgroup>
<col style="width: 11%">
<col style="width: 22%">
<col style="width: 15%">
<col style="width: 26%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th>Time <br> (months)</th>
<th>Patients at Risk <br> <span class="math inline">\(n_i\)</span></th>
<th>Failures <br> <span class="math inline">\(d_i\)</span></th>
<th>Survival Probability <br> at <span class="math inline">\(t_i\)</span></th>
<th>Cumulative Survival <br> <span class="math inline">\(S(t)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>3</td>
<td>10</td>
<td>1</td>
<td>1 - <span class="math inline">\(\frac{1}{10}\)</span> = 0.9</td>
<td>0.9</td>
</tr>
<tr class="even">
<td>4</td>
<td>9</td>
<td>1</td>
<td>1 - <span class="math inline">\(\frac{1}{9}\)</span> = 0.888</td>
<td>0.9 <span class="math inline">\(\times\)</span> 0.888 = 0.8</td>
</tr>
<tr class="odd">
<td>5</td>
<td>8</td>
<td>1</td>
<td>1 - <span class="math inline">\(\frac{1}{8}\)</span> = 0.875</td>
<td>0.8 <span class="math inline">\(\times\)</span> 0.875 = 0.7</td>
</tr>
<tr class="even">
<td>6</td>
<td>7</td>
<td>1</td>
<td>1 - <span class="math inline">\(\frac{1}{7}\)</span> = 0.857</td>
<td>0.7 <span class="math inline">\(\times\)</span> 0.857 = 0.6</td>
</tr>
<tr class="odd">
<td>7</td>
<td>6</td>
<td>1</td>
<td>1 - <span class="math inline">\(\frac{1}{6}\)</span> = 0.833</td>
<td>0.6 <span class="math inline">\(\times\)</span> 0.833 = 0.5</td>
</tr>
<tr class="even">
<td>8</td>
<td>5</td>
<td>2</td>
<td>1 - <span class="math inline">\(\frac{2}{5}\)</span> = 0.6</td>
<td>0.5 <span class="math inline">\(\times\)</span> 0.6 = 0.3</td>
</tr>
<tr class="odd">
<td>10</td>
<td>3</td>
<td>1</td>
<td>1 - <span class="math inline">\(\frac{1}{3}\)</span> = 0.667</td>
<td>0.3 <span class="math inline">\(\times\)</span> 0.667 = 0.2</td>
</tr>
<tr class="even">
<td>11</td>
<td>2</td>
<td>1</td>
<td>1 - <span class="math inline">\(\frac{1}{2}\)</span> = 0.5</td>
<td>0.2 <span class="math inline">\(\times\)</span> 0.5 = 0.1</td>
</tr>
<tr class="odd">
<td>12</td>
<td>1</td>
<td>1</td>
<td>1 - <span class="math inline">\(\frac{1}{1}\)</span> = 0</td>
<td>0.1 <span class="math inline">\(\times\)</span> 0 = 0</td>
</tr>
</tbody>
</table>
<ul>
<li>At 3 months: 10 patients are at risk, and 1 failure occurs, so the survival probability for this period is 0.9.</li>
<li>For 4 months: 9 patients are at risk (since one patient failed at 3 months), and the survival probability is now cumulative (0.9 from the first interval multiplied by 0.888 from this interval).</li>
<li>At time 8 months: two failures occur and the survival probability drops more sharply.</li>
<li>At time 12 months: the survival probability reaches 0, indicating that all patients experienced the event (tooth filling failure) by the end of the study.</li>
</ul>
</div></div>
</section>
<section id="kaplan-meier-estimator-2" class="slide level2 smaller">
<h2>Kaplan-Meier estimator</h2>
<p><br></p>

<img data-src="presentation_files/figure-revealjs/fig-tooth-filling-1-1.png" width="960" class="r-stretch quarto-figure-center" id="fig-tooth-filling-1"><p class="caption">
Figure&nbsp;3: Kaplan-Meier survival curve for tooth filling data. The curve shows the estimated probability of survival (filling intact) over time.
</p></section>
<section id="kaplan-meier-estimator-3" class="slide level2 smaller">
<h2>Kaplan-Meier estimator</h2>
<p><em>Tooth filling example with censored data</em></p>
<div class="columns">
<div class="column" style="width:35%;">
<ul>
<li>In real life, not all patients may have complete follow-up data.</li>
<li>Some patients might drop out of the study or do not experience an event by the end of the study period.</li>
<li>Let’s update the data with censoring for two patients</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   10 obs. of  3 variables:
 $ patientID: int  1 2 3 4 5 6 7 8 9 10
 $ time     : num  10 8 11 5 4 3 7 6 12 8
 $ surv     : num  0 1 1 0 1 1 1 1 1 1</code></pre>
</div>
</div>
<ul>
<li>To get KM estimates, we can use the same Kaplan-Meier formula, but now we need to account for the censored data.</li>
<li>For censored patients, we do not count them in the number of failures, but they are still included in the “at-risk” population until they are censored.</li>
</ul>
</div><div class="column" style="width:5%;">

</div><div class="column" style="width:60%;">
<table class="caption-top">
<colgroup>
<col style="width: 10%">
<col style="width: 20%">
<col style="width: 14%">
<col style="width: 7%">
<col style="width: 24%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th>Time<br>(months)</th>
<th>Patients at Risk<br><span class="math inline">\(n_i\)</span></th>
<th>Failures<br><span class="math inline">\(d_i\)</span></th>
<th>C</th>
<th>Survival Probability <br>at <span class="math inline">\(t_i\)</span></th>
<th>Cumulative Survival<br><span class="math inline">\(S(t)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>3</td>
<td>10</td>
<td>1</td>
<td>0</td>
<td><span class="math inline">\(1 - \frac{1}{10} = 0.9\)</span></td>
<td>0.9</td>
</tr>
<tr class="even">
<td>4</td>
<td>9</td>
<td>1</td>
<td>0</td>
<td><span class="math inline">\(1 - \frac{1}{9} = 0.888\)</span></td>
<td>0.9 <span class="math inline">\(\times\)</span> 0.888 = 0.8</td>
</tr>
<tr class="odd">
<td>5</td>
<td>8</td>
<td>0</td>
<td>1</td>
<td></td>
<td>0.8</td>
</tr>
<tr class="even">
<td>6</td>
<td>7</td>
<td>1</td>
<td>0</td>
<td><span class="math inline">\(1 - \frac{1}{7} = 0.857\)</span></td>
<td>0.8 <span class="math inline">\(\times\)</span> 0.857 = 0.686</td>
</tr>
<tr class="odd">
<td>7</td>
<td>6</td>
<td>1</td>
<td>0</td>
<td><span class="math inline">\(1 - \frac{1}{6} = 0.833\)</span></td>
<td>0.686 <span class="math inline">\(\times\)</span> 0.833 = 0.571</td>
</tr>
<tr class="even">
<td>8</td>
<td>5</td>
<td>2</td>
<td>0</td>
<td><span class="math inline">\(1 - \frac{2}{5} = 0.0.6\)</span></td>
<td>0.571 <span class="math inline">\(\times\)</span> 0.6 = 0.343</td>
</tr>
<tr class="odd">
<td>10</td>
<td>3</td>
<td>0</td>
<td>1</td>
<td></td>
<td>0.343</td>
</tr>
<tr class="even">
<td>11</td>
<td>2</td>
<td>1</td>
<td>0</td>
<td><span class="math inline">\(1 - \frac{1}{2} = 0.5\)</span></td>
<td>0.343 <span class="math inline">\(\times\)</span> 0.5 = 0.171</td>
</tr>
<tr class="odd">
<td>12</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td><span class="math inline">\(1 - \frac{1}{1} = 0\)</span></td>
<td>0.171 <span class="math inline">\(\times\)</span> 0 = 0</td>
</tr>
</tbody>
</table>
<p>Censoring affects the calculations:</p>
<ul>
<li>At 5 months, one patient is censored, so we do not record a failure, and the cumulative survival rate remains unchanged.</li>
<li>At 10 months, one more patient is censored. Again, there is no effect on the failure probability, but the number of at-risk patients decreases.</li>
<li>In other words, if a patient is censored, they contribute to the number of at-risk patients until their censoring time, but they do not contribute to the event (failure) counts.</li>
</ul>
</div></div>
</section>
<section id="kaplan-meier-estimator-4" class="slide level2 smaller">
<h2>Kaplan-Meier estimator</h2>

<img data-src="presentation_files/figure-revealjs/fig-tooth-filling-2-1.png" width="960" class="r-stretch quarto-figure-center" id="fig-tooth-filling-2"><p class="caption">
Figure&nbsp;4: Kaplan-Meier survival curve for tooth filling data. The curve shows the estimated probability of survival (filling intact) over time.
</p></section>
<section id="kaplan-meier-estimator-5" class="slide level2 smaller">
<h2>Kaplan-Meier estimator</h2>
<p><em>Interpretations</em></p>
<p><br></p>
<p>The Kaplan-Meier curve shows the cumulative survival probabilities.</p>
<ul>
<li>A steeper slope indicates a higher event rate (death rate) and therefore a worse survival prognosis.</li>
<li>A flatter slope indicates a lower event rate and therefore a better survival prognosis.</li>
<li>The curve may have plateaus or flat areas, indicating periods of relatively stable survival.</li>
</ul>
</section>
<section id="kaplan-meier-estimator-6" class="slide level2 smaller">
<h2>Kaplan-Meier estimator</h2>
<p><em>Interpretations</em></p>
<p><br></p>
<p>At specific time points, we can estimate the survival probability:</p>
<ul>
<li>by locating the time point on the horizontal axis and dropping a vertical line to the curve</li>
<li>then, reading the corresponding survival probability from the vertical axis.</li>
<li>So, what is the probability that a tooth filling will last 10 months?</li>
</ul>
<div class="r-stack">
<p><img data-src="presentation_files/figure-revealjs/KM-01-1.png" class="fragment" width="500" height="500"></p>
<p><img data-src="presentation_files/figure-revealjs/KM-02-1.png" class="fragment" width="500" height="500"></p>
</div>
</section>
<section id="kaplan-meier-estimator-7" class="slide level2 smaller">
<h2>Kaplan-Meier estimator</h2>
<p><em>Interpretations</em></p>
<p><br></p>
<div class="columns">
<div class="column" style="width:40%;">
<p>If there are multiple curves representing different groups, we can compare their shapes and patterns.</p>
<ul>
<li>If the curves are parallel, it suggests that the groups have similar survival experiences.</li>
<li>If the curves diverge or cross, it indicates differences in survival between the groups.</li>
</ul>
</div><div class="column" style="width:5%;">

</div><div class="column" style="width:55%;">
<div class="cell">
<div class="cell-output-display">
<div id="fig-tooth-filling-20-part" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-tooth-filling-20-part-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="presentation_files/figure-revealjs/fig-tooth-filling-20-part-1.png" width="960">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tooth-filling-20-part-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Kaplan-Meier survival curves for a new extended study of tooth filling data, including 20 participants (10 men and 10 women).
</figcaption>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section>
<section id="comparisons-of-hazards" class="title-slide slide level1 center">
<h1>Comparisons of hazards</h1>

</section>
<section id="comparisons-of-hazards-1" class="slide level2 smaller">
<h2>Comparisons of hazards</h2>
<p><br></p>
<ul>
<li>Goal: Compare survival times across groups (e.g., men vs.&nbsp;women in a tooth filling study)</li>
<li>Problem: Survival curves may cross, i.e.&nbsp;differences are not constant over time</li>
<li>Solution: Compare <strong>hazards</strong> in the groups instead of survival probabilities</li>
<li>and we also assume that the <strong>ratio of the hazards</strong> in the two groups remains constant over time, even if the underlying hazards change.</li>
</ul>
<p><br></p>
<div class="fragment">
<p><strong>Proportional Hazards Assumption</strong></p>
<ul>
<li>Assume hazard ratio is <strong>constant</strong> over time: <span class="math display">\[
\frac{h_1(t)}{h_0(t)} = \text{constant}
\]</span></li>
<li>( h_1(t) ), ( h_0(t) ): hazards in two comparison groups at time <span class="math inline">\(t\)</span></li>
</ul>
</div>
</section>
<section id="mantel-cox-log-rank-test" class="slide level2 smaller">
<h2>Mantel-Cox (log-rank test)</h2>
<p><br></p>
<ul>
<li>Tests for <strong>differences in survival</strong> between two or more groups</li>
<li>Assumes <strong>proportional hazards</strong></li>
<li>Null hypothesis: no difference in survival curves</li>
<li>Compares the <strong>observed vs.&nbsp;expected</strong> number of events in each group</li>
<li>Test statistic follows a <strong>chi-square distribution</strong></li>
</ul>
<div class="fragment">
<p>At each time event, we can set-up a table:</p>
<table class="caption-top">
<colgroup>
<col style="width: 12%">
<col style="width: 28%">
<col style="width: 31%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><strong>Died</strong></th>
<th><strong>Survived</strong></th>
<th><strong>Total</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Group A</strong></td>
<td><span class="math inline">\(d_{jA}\)</span></td>
<td><span class="math inline">\(r_{jA} = n'_{_jA} - d_{jA}\)</span></td>
<td><span class="math inline">\(n'_{jA}\)</span></td>
</tr>
<tr class="even">
<td><strong>Group B</strong></td>
<td><span class="math inline">\(d_{jB}\)</span></td>
<td><span class="math inline">\(r_{jB} = n_{_jB} - d_{jB}\)</span></td>
<td><span class="math inline">\(n'_{jB}\)</span></td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td><span class="math inline">\(d_j = d_{jA} + d_{jB}\)</span></td>
<td><span class="math inline">\(r_j = r_{jA} + r_{jB}\)</span></td>
<td><span class="math inline">\(n'_j = n'_{jA} + n'_{jB}\)</span></td>
</tr>
</tbody>
</table>
<p>where:</p>
<ul>
<li><strong>Group A</strong> and <strong>Group B</strong> represent the two groups being compared (e.g., two different treatments, genders, etc.).</li>
<li><strong>Died</strong> (<span class="math inline">\(d_{jA}\)</span>, <span class="math inline">\(d_{jB}\)</span>): The number of individuals who experienced the event (e.g., death, tooth filling falling out) in each group.</li>
<li><strong>Survived</strong> (<span class="math inline">\(r_{jA}\)</span>, <span class="math inline">\(r_{jB}\)</span>): The number of individuals who did not experience the event (survivors, with tooth filling intact) in each group. This is calculated as the total number in the group minus the number of deaths.</li>
<li><strong>Total</strong> (<span class="math inline">\(n_A\)</span>, <span class="math inline">\(n_B\)</span>): The total number of individuals in each group at risk just before the time of an event</li>
</ul>
</div>
</section>
<section id="mantel-cox-log-rank-test-1" class="slide level2 smaller">
<h2>Mantel-Cox (log-rank test)</h2>
<p><br> <br></p>
<p>The log-rank test compares the <strong>observed</strong> number of events to the <strong>expected</strong> number of events if the survival curves were the same for all groups.</p>
<p>The <strong>expected number of events</strong> in group A at each event time is denoted by: <span class="math display">\[E(d_{jA}) = \frac{n'_{jA}d_i}{n'_j}\]</span> and analogously for group B <span class="math display">\[E(d_{jB}) = \frac{n'_{jB}d_j}{n'_j}\]</span></p>
<p>The difference between observed and expected number of events is evidence against the null hypothesis. The Mantel-Cox chi-squared (log-rank) its simple for is the combination of these differences <strong>over all the times at which deaths (events) occurred</strong>: <span class="math display">\[
\chi^2_{MC} = \sum_{j} \left( \frac{(O_{jA} - E_{jA})^2}{E_{jA}} + \frac{(O_{jB} - E_{jB})^2}{E_{jB}} \right)
\]</span></p>
<p>with 1 <span class="math inline">\(df\)</span>.</p>
</section></section>
<section>
<section id="regression-with-survival-data" class="title-slide slide level1 center">
<h1>Regression with survival data</h1>

</section>
<section id="cox-proportional-hazards-model" class="slide level2 smaller">
<h2>Cox proportional hazards model</h2>
<p><em>Studying relationship between survival time and predictors</em></p>
<p><br></p>
<p><strong>Cox PH model</strong></p>
<ul>
<li>Is used to estimate the hazard ratio for individuals based on their covariates.</li>
<li>Is used to study <strong>how different factors affect the risk</strong> of an event over time
<ul>
<li>e.g.&nbsp;Is an older patient more likely to relapse sooner than a younger one?</li>
</ul></li>
<li>The model gives <strong>relative risk</strong>, not absolute predictions of survival time . . .</li>
</ul>
<p><br></p>
<p>The risk of death at time <span class="math inline">\(t_j\)</span> for each subject in the risk set is given by: <span class="math display">\[h(t|\boldsymbol{x}) = h_0(t)\textrm{exp}(\boldsymbol{\beta}^T\boldsymbol{x})\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(h(t|\boldsymbol{x})\)</span>: hazard at time <span class="math inline">\(t\)</span> for a subject with covariates <span class="math inline">\(\boldsymbol{x}\)</span></li>
<li><span class="math inline">\(\boldsymbol{\beta}^T\boldsymbol{x}\)</span> is the matrix representation of the regression function, <span class="math inline">\(\beta_1x_1 + \beta_2x_2 + \cdots + \beta_px_p\)</span></li>
<li>and <span class="math inline">\(h_0(t)\)</span> is <strong>baseline hazard function</strong> (common to all)</li>
<li><span class="math inline">\(\exp(\boldsymbol{\beta}^T \boldsymbol{x})\)</span>: relative effect of covariates</li>
</ul>
</section>
<section id="cox-ph-model" class="slide level2 smaller">
<h2>Cox PH model</h2>
<p><br></p>
<p><em>Example with brain cancer data</em></p>
<div class="columns">
<div class="column" style="width:45%;">
<p>The <code>BrainCancer</code> data set from the <code>ISLR2</code> package contains survival times for patients with primary brain tumors undergoing treatment with radiation therapy.</p>
<p>Variables included in the study are:</p>
<ul>
<li><code>sex</code>: male or female</li>
<li><code>diagnosis</code>: meningioma, LG glioma, HG glioma, or other</li>
<li><code>loc</code>: tumor location, infratentorial or supratentorial</li>
<li><code>gtv</code>: gross tumor volume <span class="math inline">\(cm^3\)</span></li>
<li><code>ki</code>: Karnofsky index</li>
<li><code>stereo</code>: stereotatcic radiosurgery (SRS) or fractionated stereotactic (SRT) radiotherapy</li>
</ul>
</div><div class="column" style="width:5%;">

</div><div class="column" style="width:45%;">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Call:
coxph(formula = Surv(time, status) ~ sex + diagnosis + ki, data = data_brain)

  n= 87, number of events= 35 
   (1 observation deleted due to missingness)

                       coef exp(coef) se(coef)      z Pr(&gt;|z|)    
sexMale             0.11149   1.11795  0.35670  0.313 0.754608    
diagnosisLG glioma  1.01441   2.75774  0.62159  1.632 0.102687    
diagnosisHG glioma  2.22962   9.29629  0.44520  5.008  5.5e-07 ***
diagnosisOther      0.82773   2.28813  0.57751  1.433 0.151774    
ki                 -0.06624   0.93591  0.01753 -3.778 0.000158 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

                   exp(coef) exp(-coef) lower .95 upper .95
sexMale               1.1179     0.8945    0.5556    2.2493
diagnosisLG glioma    2.7577     0.3626    0.8156    9.3251
diagnosisHG glioma    9.2963     0.1076    3.8847   22.2467
diagnosisOther        2.2881     0.4370    0.7377    7.0967
ki                    0.9359     1.0685    0.9043    0.9686

Concordance= 0.782  (se = 0.038 )
Likelihood ratio test= 36.59  on 5 df,   p=7e-07
Wald test            = 34.11  on 5 df,   p=2e-06
Score (logrank) test = 40.79  on 5 df,   p=1e-07</code></pre>
</div>
</div>
</div></div>
<div class="fragment">
<p>Based on the results:</p>
<div>
<ul>
<li class="fragment">The estimated hazard ratio (HR) for a male patient is <span class="math inline">\(e^{0.11} = 1.11\)</span>. This means that men have 1.11 times the hazard of dying than women while keeping other variables constant (adjusted hazard ration, AHR).</li>
<li class="fragment">The associated p-value of 0.75 (large) indicates that this difference is not statistically significant.</li>
<li class="fragment">One-unit increase in the Karnofsky index is corresponds to a multiplier of <span class="math inline">\(e^{-0.06} = 0.94\)</span> in the chance of dying. The higher the Karnofsky index score, the lower the chance of dying at any given point in time, with this effect being highly significant <span class="math inline">\(p\)</span>-value of 0.000158.</li>
<li class="fragment">To find HR associated with for patients with 10 units higher Karnofsky index, we calculate HR as <span class="math inline">\(e^{-0.06 \times 10} = 0.54\)</span>. This means that patients with 10 units higher Karnofsky index have 0.54 times the hazard of dying compared to those with lower Karnofsky index.</li>
</ul>
</div>
</div>
</section>
<section id="cox-ph-model-1" class="slide level2 smaller">
<h2>Cox PH model</h2>
<p><br></p>
<p><em>Forest plot</em></p>
<p><br></p>
<p>Sometimes, in addition to reporting the numeric results of a Cox regression, <strong>forest plots</strong> are used to visualize HRs and their 95% confidence intervals.</p>

<img data-src="presentation_files/figure-revealjs/forest-plot-1.png" width="960" class="r-stretch"></section>
<section id="cox-ph-model-2" class="slide level2 smaller">
<h2>Cox PH model</h2>
<p><em>Likelihood ratio test, Wald test, and Score test</em></p>
<p><br></p>
<p>Cox regression output includes <strong>three overall tests</strong> to evaluate whether the covariates collectively improve the model:</p>
<div class="fragment">
<p><br></p>
<p><strong>Likelihood Ratio Test (LRT)</strong></p>
<ul>
<li>Compares the log-likelihood of:
<ul>
<li>A null model (no covariates)</li>
<li>A full model (with covariates)</li>
</ul></li>
<li>Tests whether the full model significantly improves fit</li>
</ul>
</div>
<div class="fragment">
<p><br></p>
<p><strong>Wald Test</strong></p>
<ul>
<li>Tests whether each coefficient <span class="math inline">\(\beta_i\)</span> is significantly <span class="math inline">\(\neq 0\)</span></li>
</ul>
</div>
<div class="fragment">
<p><br></p>
<p><strong>Score Test (Log-Rank Test)</strong></p>
<ul>
<li>Assesses the contribution of predictors using the <strong>expected vs.&nbsp;observed</strong> events</li>
<li>Like LRT, compares null and full models</li>
<li>Uses a <strong>chi-squared distribution</strong></li>
</ul>
</div>
</section>
<section id="cox-ph-model-3" class="slide level2 smaller">
<h2>Cox PH model</h2>
<p><em>Concordance</em></p>
<p><br></p>
<ul>
<li>Measures how well the Cox model <strong>predicts the order of events</strong></li>
<li>Assesses: Can the model correctly identify <strong>who experiences the event earlier</strong>?</li>
</ul>
<p><br></p>
<div class="fragment">
<p><strong>Interpretation:</strong></p>
<ul>
<li><strong>C-index = 0.5</strong> → No better than random guessing</li>
<li><strong>C-index = 1</strong> → Perfect prediction of event order</li>
</ul>
</div>
<div class="fragment">
<p><br></p>
<p><strong>Example:</strong></p>
<ul>
<li>A C-index of <strong>0.782</strong> means:
<ul>
<li>The model correctly orders survival times in <strong>78.2%</strong> of comparable pairs</li>
<li>In 78.2% of cases, the individual with the higher predicted risk had the event first</li>
</ul></li>
<li><strong>Standard error = 0.038</strong>:
<ul>
<li>Quantifies uncertainty around the estimate</li>
<li>Smaller SE → greater confidence in the result</li>
</ul></li>
</ul>
</div>
</section>
<section id="cox-ph-model-4" class="slide level2 smaller">
<h2>Cox PH model</h2>
<p><em>Predictions</em></p>
<p><br></p>
<p>In Cox regression, we can estimate:</p>
<div>
<ul>
<li class="fragment">the survival probability at a specific time</li>
<li class="fragment">and the hazard ratio for an individual relative to a reference individual</li>
</ul>
</div>
</section>
<section id="cox-ph-model-5" class="slide level2 smaller">
<h2>Cox PH model</h2>
<p><em>Time-dependent covariates</em></p>
<p><br></p>
<ul>
<li>So far, predictors (covariates) have been <strong>fixed</strong> over time</li>
<li>But some predictors can <strong>change during follow-up</strong></li>
<li>e.g.&nbsp;in a heart attack study, blood pressure may change over time</li>
</ul>
<div class="fragment">
<p><br> <br></p>
<p>The Cox model allows covariates <span class="math inline">\(\boldsymbol{x}(t)\)</span> to vary with time: <span class="math display">\[h(t | \boldsymbol{x}(t)) = h_0(t) \cdot \exp(\boldsymbol{\beta}^T \boldsymbol{x}(t))\]</span></p>
<ul>
<li>Follow-up time is split into <strong>intervals</strong> where covariates are constant</li>
<li>Covariates are updated at each interval to reflect changes</li>
</ul>
</div>
</section>
<section id="multiple-events-competing-risks" class="slide level2 smaller">
<h2>Multiple events: competing risks</h2>
<p><em>death from other causes</em></p>
<p><br></p>
<ul>
<li>In many studies, individuals are at risk of <strong>more than one event</strong></li>
<li>A <strong>competing risk</strong> is an event that <strong>prevents</strong> the event of interest from happening</li>
</ul>
<div class="fragment">
<p><br></p>
<p><strong>Examples:</strong></p>
<ul>
<li>Studying death from heart disease:
<ul>
<li>Death from cancer = competing risk</li>
</ul></li>
<li>Studying cancer relapse:
<ul>
<li>Death from any cause = competing risk</li>
</ul></li>
</ul>
<p><br></p>
</div>
<div class="fragment">
<p><strong>Why it matters:</strong></p>
<ul>
<li>Cox PH model assumes only <strong>one type of event</strong></li>
<li>Ignoring competing risks can <strong>overestimate</strong> the chance of the event we are interested in</li>
</ul>
</div>
<div class="fragment">
<p><br></p>
<p><strong>Beyond Cox PH model:</strong></p>
<ul>
<li>The <strong>Cumulative Incidence Function (CIF)</strong> tells us the <strong>probability of a specific event</strong> happening over time, <strong>accounting for competing events</strong></li>
<li><strong>Fine and Gray’s model</strong>, help include covariates when modeling competing risks</li>
</ul>
</div>
</section>
<section id="lab" class="slide level2 smaller">
<h2>💻 Lab</h2>
<p><br></p>
<p>In the lab there are examples of:</p>
<ul>
<li>constructing Kaplan-Meier estimator</li>
<li>comparing survival curves with the log-rank test</li>
<li>fitting Cox proportional hazards model</li>
<li>interpreting the results of the Cox model</li>
<li>predicting survival probabilities and hazard ratios</li>
<li>handling time-dependent covariates</li>
<li>dealing with competing risks using the Cumulative Incidence Function (CIF)</li>
</ul>
</section>
<section id="thank-you" class="slide level2">
<h2>Thank you</h2>
<p>Questions?</p>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="presentation_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="presentation_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="presentation_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="presentation_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="presentation_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="presentation_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="presentation_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="presentation_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="presentation_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="presentation_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="presentation_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 10,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Copied!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Copied!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp('/' + window.location.host + '/');
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>
    

</body></html>